Per-Component Changes
----------------------

.. include:: Per_Component/XMPP_release_notes.inc
.. include:: Per_Component/Mix_release_notes.inc
.. include:: Per_Component/PubSub_release_notes.inc
.. include:: Per_Component/Muc_release_notes.inc
.. include:: Per_Component/HTTP_API_release_notes.inc
.. include:: Per_Component/Push_release_notes.inc
.. include:: Per_Component/Message_release_notes.inc
.. include:: Per_Component/ACS_release_notes.inc