Tigase Advanced Clustering Strategy (ACS) 3.2.0 Release Note
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



Major Changes
~~~~~~~~~~~~~

-  Deprecate Deprecate PartitionedStrategy in ACS-PubSub



All Changes
~~~~~~~~~~~~~

-  `#acs-8 <https://projects.tigase.net/issue/acs-8>`__: Fix NotAuthorizedException: Session has not been yet authorised. in OnlineUsersCachingStrategy

-  `#acsmix-1 <https://projects.tigase.net/issue/acsmix-1>`__: Implement clustering support for MIX

-  `#acsmix-3 <https://projects.tigase.net/issue/acsmix-3>`__: Fix NPE in DefaultPubSubLogic

-  `#acsmix-4 <https://projects.tigase.net/issue/acsmix-4>`__: Fix NPE in DefaultPubSubLogic.subscribersOfNotifications()

-  `#acsmuc-23 <https://projects.tigase.net/issue/acsmuc-23>`__: Fix NPE in ClusteredRoomStrategyV2

-  `#acsmuc-25 <https://projects.tigase.net/issue/acsmuc-25>`__: Fix NPE in OccupantChangedPresenceCmd

-  `#acspubsub-20 <https://projects.tigase.net/issue/acspubsub-20>`__: Fix NPE in pubsub-nodes-changed-cmd

-  `#acspubsub-21 <https://projects.tigase.net/issue/acspubsub-21>`__: Fix Multiple notifications for single publication

-  `#acspubsub-22 <https://projects.tigase.net/issue/acspubsub-22>`__: Fix Presences informations are kept indefinitely

-  `#acspubsub-24 <https://projects.tigase.net/issue/acspubsub-24>`__: Fix caps-changed-cmd not processed correctly

-  `#acspubsub-25 <https://projects.tigase.net/issue/acspubsub-25>`__: Deprecate PartitionedStrategy

-  `#acspubsub-27 <https://projects.tigase.net/issue/acspubsub-27>`__: Review and improve clustering documentation
