Tigase MIX 1.0.0 Release Notes
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Major Changes
~~~~~~~~~~~~~~

This is the introductory version of `MIX specification family <https://xmpp.org/extensions/xep-0369.html#family>`__


All Changes
~~~~~~~~~~~~~~

-  `#mix-2 <https://projects.tigase.net/issue/mix-2>`__:Implement XEP-0369: Mediated Information eXchange (MIX)

-  `#mix-3 <https://projects.tigase.net/issue/mix-3>`__:Implement XEP-0406: Mediated Information eXchange (MIX): MIX Administration

-  `#mix-6 <https://projects.tigase.net/issue/mix-6>`__:Create tests for MIX CORE & Participants Server Requirements

-  `#mix-8 <https://projects.tigase.net/issue/mix-8>`__:Improve caching

-  `#mix-9 <https://projects.tigase.net/issue/mix-9>`__:Add support for MIX-MUC integration

-  `#mix-10 <https://projects.tigase.net/issue/mix-10>`__:Invalid response for disco#items

-  `#mix-14 <https://projects.tigase.net/issue/mix-14>`__:Add configuration to limit who can create channels in component

-  `#mix-15 <https://projects.tigase.net/issue/mix-15>`__:NPE in MAMItemHandler

-  `#mix-16 <https://projects.tigase.net/issue/mix-16>`__:Add MIX to installer as option.

-  `#mix-17 <https://projects.tigase.net/issue/mix-17>`__:Could not parse new configuration of channel: PubSubException: Only participants and information nodes are supported!

-  `#mix-18 <https://projects.tigase.net/issue/mix-18>`__:NPE when sending requests to removed channel nodes

-  `#mix-19 <https://projects.tigase.net/issue/mix-19>`__:MAM:2 is not advertised

-  `#mix-20 <https://projects.tigase.net/issue/mix-20>`__:MIX component is broadcasting messages with bare JID

-  `#mix-21 <https://projects.tigase.net/issue/mix-21>`__:Possibility of duplicated subscription of a node

-  `#mix-22 <https://projects.tigase.net/issue/mix-22>`__:Nickname not returned in response after being set

-  `#mix-23 <https://projects.tigase.net/issue/mix-23>`__:Remove banned participants from participants list and subscriptions

-  `#mix-24 <https://projects.tigase.net/issue/mix-24>`__:NPE in MIXProcessor

-  `#mix-25 <https://projects.tigase.net/issue/mix-25>`__:Create MIX component documentation and publish it

-  `#mix-26 <https://projects.tigase.net/issue/mix-26>`__:Allow installation admins to manager MIX channels if domain admins are allowed

-  `#mix-27 <https://projects.tigase.net/issue/mix-27>`__:MIX-MUC message duplication

-  `#mix-28 <https://projects.tigase.net/issue/mix-28>`__:NPE in ``Affiliations.getSubscriberAffiliation``

-  `#mix-29 <https://projects.tigase.net/issue/mix-29>`__:Weird "open channel" behaviour
