Tigase MUC 3.2.0 Release Notes
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Major Changes
~~~~~~~~~~~~~~

-  Bring MUC specification support up to date

-  Improve handling of multiple user session using same nickname

-  Fixes and improvements to ad-hoc scripts


All Changes
~~~~~~~~~~~~

-  `#muc-133 <https://projects.tigase.net/issue/muc-133>`__: Add component option to let only admins create rooms

-  `#muc-134 <https://projects.tigase.net/issue/muc-134>`__: Better MUC Converter log

-  `#muc-136 <https://projects.tigase.net/issue/muc-136>`__: MUC specification supported by Tigase MUC is out of data

-  `#muc-137 <https://projects.tigase.net/issue/muc-137>`__: Add support for <iq/> forwarding with multiple resources joined

-  `#muc-138 <https://projects.tigase.net/issue/muc-138>`__: tigase@muc.tigase.org kicks my clients if I use them both

-  `#muc-139 <https://projects.tigase.net/issue/muc-139>`__: Create script to (mass) delete MUC rooms

-  `#muc-140 <https://projects.tigase.net/issue/muc-140>`__: There is no empty ``<subject/>`` element for persistent room sent after re-joining

-  `#muc-141 <https://projects.tigase.net/issue/muc-141>`__: StringIndexOutOfBoundsException in IqStanzaForwarderModule

-  `#muc-142 <https://projects.tigase.net/issue/muc-142>`__: NullPointerException when processing message with subject

-  `#muc-143 <https://projects.tigase.net/issue/muc-143>`__: Fix MUC scripts: "No such property: mucRepository for class: tigase.admin.Script151"

-  `#muc-144 <https://projects.tigase.net/issue/muc-144>`__: No signature of method: tigase.muc.cluster.RoomClustered.addAffiliationByJid()
