[[QuickStart]]
= Quick Start Guide
:author: Artur Hefczyc <artur.hefczyc@tigase.net>
:version: v2.1, June 2014: Reformatted for v8.0.0.

== Minimum Requirements

Before you begin installing Tigase server onto your system, please make sure the minimum requirements are met first:

- *Java Development Kit (JDK) 11 (LTS)* - We recommend OpenJDK
- *Administrator access* - We recommend that you install Tigase Server from a user login with administrator access.

IMPORTANT: You should always run the latest point/bugfix release of the recommended JDK.

NOTE: While it should be possible to use newer versions of the JDK, we don't guarantee it and we recommend using the one mentioned above.

== Contents

This is a set of documents allowing you to quickly start with our software. Every document provides an introduction to a single topic allowing you to start using/developing or just working on the subject. Please have a look at the documents list below to find a topic you are looking for. If you don't find a document for the topic you need please link:http://www.tigase.net/contact[let us know].

- xref:webinstall[Installation Using Web Installer]
- xref:manualinstall[Manual installation in console mode]
- xref:windowsInstallation[Installing Tigase on Windows]
- xref:setupTigaseServer[Network settings for Tigase]
- xref:tigaseScriptStart[Running Tigase XMPP Server as a service]
