.. _serverMonitoring:

Server Monitoring
-----------------------

All the documentation and resources related to the Tigase server monitoring.

-  :ref:`Setting up Remote Monitoring in the Server<Setting-Up-Remote-Monitoring-in-the-Server>`

-  :ref:`Statistics Logger Configuration<Configuration-of-statistics-loggers>`

-  :ref:`Retrieving Statistics from the Server<Retrieving-statistics-from-the-server>`

-  :ref:`Monitor Component<Monitor-Component>`