[[clComp]]
= cl-comp
:author: Daniel Wisnewski <daniel.wisnewski@tigase.net>
:version: v2.0, June 2017: Reformatted for Kernel/DSL

*Description:* Container specifying cluster component configuration.

*Default value:* By default, the cl-comp container is not listed in the `config.tdsl` file.

*Example:*
[source,dsl]
-----
'cl-comp' {
    <configuration>
}
-----

== connect-all
The `cluster-connect-all` property is used to open active connections to all nodes listed in the xref:clusterNodes[+cluster-nodes+] configuration property. This property should be used only on the node which is added to the live cluster at later time. Normally this new cluster node is not listed in the configuration of the existing cluster nodes. This is why they can not open connections the new node. The new node opens connection to all existing nodes instead. False is the default value and you can skip this option if you want to have it switched off which it is by default.

*Example*
[source,dsl]
-----
'cl-comp' {
    'connect-all' = true
}
-----

This replaces the `--cluster-connect-all` property.

*Available since:* 8.0.0
