[[clusterPortDelayListening]]
= client-port-delay-listening
:author: Daniel Wisnewski
:version: v2.0, June 2017: Reformatted for Kernel/DSL

*Description:* The property allows to enabled or disable delaying of listening for client connections *in cluster mode* until the cluster is correctly connected.

*Default value:* `true`

*Example:*
[source,dsl]
-----
<component> {
    'port-delay-listening' = false
  }
-----

*Possible values:* `true`, `false`

In cluster mode, in order to ensure correct user status broadcast, we are delaying opening client ports (components: `c2s`, `ws2s`, `bosh`) and enable those only after cluster is fully and correctly connected (i.e. either there is only single node or in case of multiple nodes all nodes connected correctly).

It's possible to enable/disable this on per-component basis with the following configuration:

[source,dsl]
-----
bosh {
    'port-delay-listening' = true
}
c2s {
    'port-delay-listening' = true
}
ws2s {
    'port-delay-listening' = true
}
-----

Maximum delay time depends on the component and it's multiplication of `ConnectionManager` default connection delay times `30s` - in case of client connection manager this delay equals 60s.

NOTE: Only applicable if *Cluster Mode* is active!

*Available since:* 7.1.0
