[[dataSource]]
= authRepository
:author: Daniel Wisnewski <daniel.wisnewski@tigase.net>
:version: v2.0, June 2017: Reformatted for Kernel/DSL

*Description:* Container specifying repository URIs. This container replaces the old `auth-db-uri` and `user-db-uri` property types.

*Default value:*
[source,dsl]
-----
dataSource {
    default () {
        uri = 'jdbc:mysql://localhost/tigasedb?user=tigase&password=tigase12'
}
-----
Once your configuration is setup, you will see the uri of your user database here. If other databases need to be defined, they will be listed in the same dataSource bean.

*Example:*
[source,dsl]
-----
dataSource {
    default () {
        uri = 'jdbc:mysql://localhost/tigasedb?user=tigase&password=tigase12'
    }
    'default-auth' () {
        uri = 'jdbc:mysql://localhost/tigasedbath?user=tigase&password=tigase12'
    }
}
-----

*Possible values:* Broken down list of customized names for DB URIs. Each name must have a defined uri property. DB name can be customized by the bean name.

NOTE: URI name may be used as shorthand to define DB location URI in other containers, so be sure to name them uniquely.

NOTE: default () URI setting replaces the `user-db-uri` as well as the `auth-repo-uri` property.

== MSSQL
MSSql support works out of the box, however Tigase provides an open source driver for the database. We recommend using Microsoft's own driver for better functionality.
[source,dsl]
-----
dataSource () {
    default () {
        uri = 'jdbc:jtds:sqlserver://localhost;databaseName=tigasedb;user=tigase_user;password=tigase_pass;schema=dbo;lastUpdateCount=false;cacheMetaData=false'
    }
}
-----
Where the uri is divided as follows:
jdbc:<driver>:sqlserver://<server address>;databaseName=<database name>;user=<username for db>;password=<password for db>;schema=dbo;lastUpdateCount=false;cacheMetaData=false
We do not recommend modification of schema and onward unless you are explicit in your changes.


== MongoDb
For using mongoDB as the repository, the setting will look slightly different:
[source,dsl]
-----
dataSource () {
    default () {
        uri = 'mongodb://username:password@localhost/dbname'
    }
}
-----

[[dataRepoPoolSize]]
== pool-size
`DataSource` is an abstraction layer between any higher level data access repositories such as `userRepository` or `authRepository` and SQL database or JDBC driver to be more specific.
Many implementations use `DataSource` for DB connections and in fact on many installations they also share the same DataRepository instance if they connect to the same DB. In this case it is desired to use a specific connection pool on this level to an avoid excessive number of connections to the database.

To do so, specify the number of number of database connection as an integer:

[source,dsl]
-----
dataSource {
    default () {
        uri = 'jdbc:mysql://localhost/tigasedb?user=tigase&password=tigase12'
        'pool-size' = '50'
    }
}
-----

By default, the number of connections is 10.

*Available since:* 8.0.0
