[[external]]
= ext
:author: Artur Hefczyc <artur.hefczyc@tigase.net>
:version: v2.0, June 2017: Reformatted for Kernel/DSL

*Description:* This property defines parameters for external component connections.

The component is loaded the same way as all other Tigase components. In your `config.tdsl` file you need to add the external class:

[source,dsl]
-----
ext (class: tigase.server.ext.ComponentProtocol) {}
-----

This will load the component with an empty configuration and is practically useless. You have to tell the component on what port to listen to (or on what port to connect to) and external domains list with passwords.

Those values need to be configured while the Tigase XMPP Server is running using XMPP ad-hoc commands such as `Add new item`, `Update item configuration` and `Remove an item` available at the JID of the external component which you have just enabled (`ext@your-server-domain`).


*Possible values:* external domains parameters list.

*Available since:* 4.3.0

*Removed in:* 8.0.0
