[[stringprepProcessor]]
= stringprep-processor
:author: Artur Hefczyc <artur.hefczyc@tigase.net>
:version: v2.0, June 2017: Reformatted for Kernel/DSL

*Description:* The `'stringprep-processor'` property sets the stringprep processor for all JIDs handled by Tigase. The default 'simple' implementation uses regular expressions to parse and check the user JID. Although it does not fulfill the RFC-3920 requirements, it also puts much less stress on the server CPU, hence impact on the performance is very low.

Other possible values are:

`'libidn'` - provides full stringprep processing exactly as described in the RFC-3920. It requires lots of CPU power and significantly impacts performance.

`'empty'` - doesn't do anything to JIDs. JIDs are accepted in the form they are received. No impact on the performance and doesn't use any CPU. This is suitable for use in automated systems where JIDs are generated by some algorithm, hence there is no way incorrect JIDs may enter the system.

*Default value:* `simple`

*Example:* `'stringprep-processor' = 'libidn'`

*Possible values:* `simple|libidn|empty`

*Available since:* 8.0.0
