[[vhostPresenceForwardJid]]
= vhost-presence-forward-jid
:author: Artur Hefczyc <artur.hefczyc@tigase.net>
:version: v2.1, August 2017: Reformatted for Kernel/DSL

*Default value:* `<null>`

*Example:* `'vhost-presence-forward-jid' = 'presence-collector@domain.com'`

*Possible values:* valid JID.

*Description:* This is a global property for presence forwarding function for the installation. All user status presences will be forwarded to given XMPP address which can be a component or any other XMPP entity. If the destination entity is a bot connected via c2s connection it probably should be addressed via full JID (with resource part) or the standard XMPP presence processing would refuse to deliver presences from users who are not in the contact list.

This is a global property which is overridden by settings for particular vhost.

The null value is used as a default when no configuration is set. This settings is useful for installations with many virtual hosts listed in the `init.property` file for which there is no individual settings specified. It enables the ability to configure default values for all of them, instead of having to provide individual configuration for each vhost.

It is also applied as a default value for all new vhosts added at run-time.

This may be used on a per-vhost basis

[source,dsl]
-----
'virtual-hosts' = [ 'domain3:vhost-presence-forward-jid = presence-collector@domain.com' ]
-----

*Available since:* 8.0.0
