[[vhostTlsRequired]]
= vhost-tls-required
:author: Artur Hefczyc <artur.hefczyc@tigase.net>
:version: v2.1, August 2017: Reformatted for Kernel/DSL

*Default value:* `false`

*Example:* `'vhost-tls-required' = true`

*Possible values:* `true|false`

*Description:* This property is a global settings to switch on/off TLS required mode on the Tigase installation. Setting this property to `false` does not turn TLS off. TLS is still available on the server but as an option and this is the client's decision whether to use encryption or not. If the property is set to true the server will not allow for user authentication or sending any other user data before TLS handshaking is completed.

This is a global property which is overridden by settings for particular vhost.

The `false` value is used as a default when no configuration is set. This settings is useful for installations with many virtual hosts listed in the `init.property` file for which there is no individual settings specified. It allows admins to configure default values for all of them, instead of having to provide individual configuration for each vhost.

It is also applied as a default value for all new vhosts added at run-time.

This may be used on a per-vhost basis

[source,dsl]
-----
'virtual-hosts' = [ 'domain3:vhost-tls-required = true' ]
-----

*Available since:* 8.0.0
