[[vhostMaxUsers]]
= vhost-max-users
:author: Artur Hefczyc <artur.hefczyc@tigase.net>
:version: v2.1, August 2017: Reformatted for Kernel/DSL

*Default value:* `0`

*Example:* `'vhost-max-users' = '1000'`

*Possible values:* integer number.

*Description:* The `vhost-max-users` property specifies how many user accounts can be registered on the installations for all vhosts.

*0 - zero* means unlimited and this is a default. Otherwise greater than zero value specifies accounts number limit.

This is a global property which is overridden by settings for particular vhost.

The default setting is used for all virtual hosts for which the configuration is not defined. This settings is most useful for installations with many virtual hosts listed in the `init.property` file for which there is no individual settings specified. It provides an ability to use default values for all of them, instead of having to provide individual configuration for each vhost.

This is a global property which is overridden by settings for particular vhost.

[source,dsl]
-----
'virtual-hosts' = [ 'domain3:vhost-max-users = 200' ]
-----

*Available since:* 8.0.0
