version: 40
imports:
- projectPath: Templates
  revision: 0.0.8
jobs:
- name: Maven CI
  jobExecutor: linux
  steps:
  - !UseTemplateStep
    name: maven build & deploy
    templateName: Tigase Server - Maven build & deploy
    paramMatrix:
    - name: timestamp-to-make-distinct
      valuesProvider: !ScriptingValues
        scriptName: getDateTimestamp
      secret: false
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger {}
  projectDependencies:
  - projectPath: tigase/_server/tigase-utils
    buildProvider: !LastFinishedBuild
      jobName: Maven CI
    artifacts: '**'
  - projectPath: tigase/_server/tigase-xmltools
    buildProvider: !LastFinishedBuild
      jobName: Maven CI
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
  postBuildActions:
  - !SendNotificationAction
    condition: failed
    receivers: group(TigaseCoreTeam)
