[[stringprepProcessor]]
--stringprep-processor
======================
Artur Hefczyc <artur.hefczyc@tigase.net>
v2.0, June 2014: Reformatted for AsciiDoc.
:toc:
:numbered:
:website: http://tigase.net/
:Date: 2013-02-10 01:29

*Default value:* +simple+

*Example:* +--stringprep-processor = libidn+

*Possible values:* +simple|libidn|empty+

*Description:* The property sets the stringprep processor for all JIDs handled by the Tigase server. The default 'simple' implementation uses regular expressions to parse and check the user JID. It does not fulfils the RFC-3920 requirements but also puts much less stress on the server CPU, hence impact on the performance is very low. 

Other possible values are: 

'libidn' - provides full stringprep processing exactly as described in the RFC-3920. It requires lots of CPU power and significantly impacts performance.

'empty' - doesn't do anything to JIDs. JIDs are accepted in the form they are received. No impact on the performance and doesn't use any CPU. Suitable for use in automated systems where JIDs are generated by some algorithm, hence there is no way incorrect JIDs may enter the system.

*Available since:* 5.0.0

