[[vhostAnonymousEnabled]]
--vhost-anonymous-enabled
=========================
Artur Hefczyc <artur.hefczyc@tigase.net>
v2.0, June 2014: Reformatted for AsciiDoc.
:toc:
:numbered:
:website: http://tigase.net/
:Date: 2013-02-22 02:37

*Default value:* +true+

*Example:* +--vhost-anonymous-enabled = false+

*Possible values:* +true|false+

*Description:* The property specifies whether anonymous user login is allowed for the installation for all vhosts. 

This is a global property which is overridden by settings for particular vhost.

A default settings for all virtual hosts for which the configuration is not defined. This settings is useful mostly for installations with many virtual hosts listed in the +init.property+ file for which there is no individual settings specified. It allows to configure a default values for all of them, instead of having to provide individual configuration for each vhost.

It is also applied as a default value for all new vhosts added at run-time.

*Available since:* 5.2.0

