[[vhostTlsRequired]]
--vhost-tls-required
====================
Artur Hefczyc <artur.hefczyc@tigase.net>
v2.0, June 2014: Reformatted for AsciiDoc.
:toc:
:numbered:
:website: http://tigase.net/
:Date: 2013-02-22 03:05

*Default value:* +false+

*Example:* +--vhost-tls-required = true+

*Possible values:* +true|false+

*Description:* The property is a global settings to switch on/off TLS required mode on the Tigase installation. Setting this property to +false+ does not turn TLS off. The TLS is still available on the server but as an option and this is the client's decision whether to use encryption or not. If the property is set to true the server will not allow for user authentication or sending any other user data before TLS handshaking is completed.

This is a global property which is overridden by settings for particular vhost.

A default settings for all virtual hosts for which the configuration is not defined. This settings is useful mostly for installations with many virtual hosts listed in the +init.property+ file for which there is no individual settings specified. It allows to configure a default values for all of them, instead of having to provide individual configuration for each vhost.

It is also applied as a default value for all new vhosts added at run-time.

*Available since:* 5.2.0

