-- QUERY START:
create table tig_stats_log (
  lid            bigint                    generated by default as identity not null,
  ts             TIMESTAMP                 DEFAULT CURRENT_TIMESTAMP,
  hostname       varchar(2049)    NOT NULL,
  cpu_usage      double precision not null default 0,
  mem_usage      double precision not null default 0,
  uptime         bigint           not null default 0,
  vhosts         int              not null default 0,
  sm_packets     bigint           not null default 0,
  muc_packets    bigint           not null default 0,
  pubsub_packets bigint           not null default 0,
  c2s_packets    bigint           not null default 0,
  ws2s_conns     bigint           not null default 0,
  s2s_packets    bigint           not null default 0,
  ext_packets    bigint           not null default 0,
  presences      bigint           not null default 0,
  messages       bigint           not null default 0,
  iqs            bigint           not null default 0,
  registered     bigint           not null default 0,
  c2s_conns      int              not null default 0,
  ws2s_packets   int              not null default 0,
  bosh_conns     int              not null default 0,
  s2s_conns      int              not null default 0,
  sm_sessions    int              not null default 0,
  sm_connections int              not null default 0,
  primary key (ts, hostname)
);
-- QUERY END: