[[tigase3xconfiguration]]
= Configuration Wizards
:author: Artur Hefczyc <artur.hefczyc@tigase.net>
:version: v2.0, June 2014: Reformatted for v8.0.0.

You can use configuration generators to easily and quickly create configuration files for every complex case.

To make it easier for average administrators or people who run the server for the first time or even for those who want to quickly test *Tigase* server in different scenarios configuration generators have been created. For each generator you can have also a few extra options which allows you to create configuration which you don't need to change for some time.

A few definitions first to make it easier to read the rest:

. *sm* - session manager component.
. *c2s* - client connection manager component
. *s2s* - server connection manager component
. *ext2s* - external component connection manager

The are 3 generators currently available:

. `'config-type' = 'default'` - creating configuration file with all available components. That is: +sm, c2s, s2s, ext2s+, +monitor+.
. `'config-type' = 'session-manager'` - creating configuration for instance with session manager and external component only. This is useful for distributed installation where you want to have session manager installed on separate machine and components managing network connections on different machines (one or more). Components included in configuration are: +sm+ and +ext2s+.
. `'config-type' = 'connection-managers'` - creating configuration for instance with components managing network connections. This is useful for distributed installation where you want to have session manager installed on separate machine and components managing network connections on different machines (one or more). Components included in configuration are: +c2s, s2s, ext2s+.
