Using Tigase
==============

This section keeps set of documents which apply to all the Tigase server version and contain more generic or introductory information on general use and features.

-  :ref:`Tigase Log Guide<Tigase-Log-Guide>`

-  :ref:`Debugging Tigase<Debuging-Tigase>`

-  :ref:`Basic System Checks<Basic-System-Checks>`

-  :ref:`Add and Manage Domains<addManageDomain>`

-  :ref:`Presence Forwarding<Presence-Forwarding>`

-  :ref:`Watchdog<Watchdog>`

   1. :ref:`Runtime Environment Tip<Tigase-Tip-Checking-the-Runtime-Environment>`

   2. :ref:`Checking Cluster Connections<Checking-Cluster-Connections>`

   3. :ref:`Best Practices for Connecting to Tigase XMPP server From Web Browser<Best-Practices-for-Connecting-to-Tigase-XMPP-server-From-Web-Browser>`

-  :ref:`Scripting Support in Tigase<Scripting-support-in-Tigase>`

   1. :ref:`Scripting Introduction - Hello World!<Scripting-Introduction - Hello-World!>`

   2. :ref:`Tigase Scripting Version 4.4.x Update for Administrators<Tigase-Scripting-Version-4.4.x-Update-for-Administrators>`

   3. :ref:`Tigase and Python Scripting<Tigase-and-Python>`

-  :ref:`Configuration Wizards<tigase3xconfiguration>`
