[[licensing]]
Licensing and Open Source
=========================
:author: Daniel Wisnewski
:date: 2015-11-01 11:24
:versionL v1.0 November 2015

:toc:
:numbered:
:website: http://www.tigase.net

As mentioned previously, Tigase is open source under AGPLv3.  If you are not familiar with open source software, or the environment, here are some frequently asked questions that might provide some answers.

*What does open source mean?* +
This means that Tigase's source code is available to the public to see how Tigase works.  There are no 'black boxes' for packets where things just happen, everything is out in the open, whereas other companies may consider this propitiatory information.
In addition, we have the benefit of many talented people working with Tigase to constantly improve Tigase server and related projects.  These people not only include the Tigase development team, but other members of the community who submit code improvements, patches, enhancements, or other changes to Tigase.

*Does this mean that the binaries are open to malicious code?* +
Although we accept patches from contributors, our repository does not accept them directly. Code may be submitted through our projects.tigase.org page and our developers will review the code before it is added.  All builds are tested for functionality and security when they are built.

*Does this mean it is less secure?* +
Not at all.  Although anybody can see the source code, and know how Tigase works; your installation, connections, and settings are uniquely yours.  Tigase is regularly tested and written to be as secure as possible using the latest encryption and secure connection protocols.

*Is Tigase free?* +
Tigase is free for download and use in it's unmodified state.  Our commercial grade products such as Advanced Clustering Strategy is available for free use for testing & development.

*Does this mean I cannot use it in my product or commercial environment?* +
Not necessarily, consult the Affero General Public License Agreement v3 to see if your use qualifies.  Tigase is offered under commercial license if your use is not covered by AGPLv3.

*Are there options for closed code or extensions?* +
Yes!  Commercial licenses can be custom made for each client, and software written for your company may be made private or part of our open source distributions at your discretion.

*Can I contribute code?* +
Sure!  Register an account in link:https://projects.tigase.org/account/register[here] and submit patches through our redmine!
