[[keytoolKeystore]]
= Server Certificate Using Keytool and Keystore
:author: Bartosz Malkowski <bmalkowski@tigase.pl>
:version: v2.0, June 2014: Reformatted for AsciiDoc.
:date: 2010-04-06 21:18

:toc:
:numbered:
:website: http://tigase.net

To allow secure connections through SSL or TLS channel you need a SSL certificate.

The main purpose of SSL certificate is to provide connecting entity with proof of identity of your server. A Significant role in proving the identity of your server is played by a trusted third party - usually the issuer of the certificate.

Certificate issued by trusted third parties usually come with a cost. However, you can also use self signed certificate which works just as well. The downside is it gives an authentication warning on client software upon connection.

Tigase server binary package and source repositories contain so-called "dummy" certificates which do not refer to any real site name. This certificate is temporary and should be used only for initial testing of your server. It should be replaced with either a self signed certificate or one issued by trusted third party organization as soon as possible.

Here are instructions how to install certificates for Tigase server.

_Please note! You must use the *keytool* program included in JDK-1.6 or later. The utility included in earlier versions can not import third party signed certificates correctly._

== Self Signed Certificate

If you don't have a third party signed certificate, you should generate a self-signed certificate.

Some XMPP clients don't work correctly with DSA keys, so we need to use RSA algorithm for generation. To generate private and public keypair, you should use keytool with the following commands:

[source,sh]
-----
keytool -genkey -alias yourdomain -keystore rsa-keystore \
    -keyalg RSA -sigalg MD5withRSA
-----

Where +yourdomain+ is a domain part of _JIDs_ on your _XMPP_ server. If you want to have TLS support for virtual domains, you have to create certificate for each virtual domain. If you have just one domain, or for some reason you have to use one certificate for all domains, use +default+ as an alias.

Now, enter the password to protect the keystore:

[source,sh]
-----
Enter keystore password: 123456
-----

The keytool will ask several questions about the certificate data. First question is very important! You must enter the hostname of your XMPP server!!

[source,sh]
-----
What is your first and last name?
  [Unknown]: jabber.myserver.org
What is the name of your organizational unit?
  [Unknown]:
What is the name of your organization?
  [Unknown]:
What is the name of your City or Locality?
  [Unknown]:
What is the name of your State or Province?
  [Unknown]:
What is the two-letter country code for this unit?
  [Unknown]:
Is CN=jabber.myserver.org, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown correct?
  [no]: yes
-----

In last step you can enter a new password for the certificate key. At the moment different passwords for both keystore and keys are not supported so you must have the same passwords for each.

[source,sh]
-----
Enter key password for <mykey>
             (RETURN if same as keystore password):
-----

Now you have to copy the rsa-keystore file to directory certs/ in your tigase server installation directory. The file may be installed in different location, but then corrections to config file are required. Refer to xref:manualconfig[manual configuration] for details.

== Certificate from Certificate Authority

If you don't have third-party signed certificate yet but you want to have one, you could obtain it from link:http://www.cacert.org/[cacert.org] for free.

First, you have to generate a Certificate Request using keytool:

[source,sh]
-----
keytool -certreq -alias yourdomain -keystore rsa-keystore
-----

Where +yourdomain+ is a domain name for which this certificate is generated. If you need support for multiple virtual domains, you need to have certificate for each domain separately and assign proper alias to the certificates. If you have just one domain or for some reason you want to use one certificate use +default+ as an alias for all domains.

Keytool generates the request:

[source,bash]
------
-----BEGIN NEW CERTIFICATE REQUEST-----
MIIBrzCCARgCAQAwbzEQMA4GA1UEBhMHVW5rbm93bjEQMA4GA1UECBMHVW5rbm93bjEQMA4GA1UE
BxMHVW5rbm93bjEQMA4GA1UEChMHVW5rbm93bjEQMA4GA1UECxMHVW5rbm93bjETMBEGA1UEAxMK
c2VydmVyLm9yZzCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAs73Y70725OcG0j4kpCfDX59e
qhz2gdGOO0LyMO7rm4m+ZCenq8E88M0RJ8/LV/7q0mtOAzbI8dtXZnmJ74xihCH8ZTFpVDMyFWgk
WCj2kz+IUD9vWt6i1UepSkr1a/jYmVMN3RSaoS+j+QLBsJ4rWeOHgIdbiF5tnMhoZMXU//0CAwEA
AaAAMA0GCSqGSIb3DQEBBAUAA4GBAHY5r9rftqiKESbbkCcfVhvnUqN4aMTC8/zXWwzBX8guC0kd
H46+p6eizwJg6p+h6rqShG2OqXCPrJzO3buHr1jEWRTlB8l5CM53L/xq61nYuaSf5R7Vv/RX2+aD
JyoBqYIoSUED0+Sjhej0SUPTOdpA/bfnqdfdtckday4vsLPC
-----END NEW CERTIFICATE REQUEST-----
------

Now send the request to your Certificate Authority. The CA issues a signed certificate and sends it to you. It may may look like:

[source,bash]
------
-----BEGIN CERTIFICATE-----
MIICUDCCAbkCBEUqAK0wDQYJKoZIhvcNAQEEBQAwbzEQMA4GA1UEBhMHVW5rbm93bjEQMA4GA1UE
CBMHVW5rbm93bjEQMA4GA1UEBxMHVW5rbm93bjEQMA4GA1UEChMHVW5rbm93bjEQMA4GA1UECxMH
VW5rbm93bjETMBEGA1UEAxMKc2VydmVyLm9yZzAeFw0wNjEwMDkwNzU2MjlaFw0wNzAxMDcwNzU2
MjlaMG8xEDAOBgNVBAYTB1Vua25vd24xEDAOBgNVBAgTB1Vua25vd24xEDAOBgNVBAcTB1Vua25v
d24xEDAOBgNVBAoTB1Vua25vd24xEDAOBgNVBAsTB1Vua25vd24xEzARBgNVBAMTCnNlcnZlci5v
cmcwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBALO92O9O9uTnBtI+JKQnw1+fXqoc9oHRjjtC
8jDu65uJvmQnp6vBPPDNESfPy1f+6tJrTgM2yPHbV2Z5ie+MYoQh/GUxaVQzMhVoJFgo9pM/iFA/
b1reotVHqUpK9Wv42JlTDd0UmqEvo/kCwbCeK1njh4CHW4hebZzIaGTF1P/9AgMBAAEwDQYJKoZI
hvcNAQEEBQADgYEAQqRPdkbc/pdDcPIWOThn2XPp0gitPkXq89ZM1mb0Pib1OISj9ekjqhEZz0UA
cI6g1XttpY6hKi6Gg+mRbwiHNVebkDLamE2UIcVJ1wBtowYeOcV1CcLnlj91ScMKNhfD5ebQL+be
tWWrJX3ep+80kF/NdVkc7htGOhLebopp8SQ=
-----END CERTIFICATE-----
------

Save the Certificate to a disk file.

Now that you have third-party signed certificate, you have to import it with *keytool* program to server certificate storage.

_Note! You must have a root CA certificate!!! You can download the cert from CA (ie.: root.crt) and import:_

[source,sh]
-----
keytool -import -keystore rsa-keystore -file root.crt \
    -alias root
-----

Last step is import the Certificate to your keystore:

[source,sh]
-----
keytool -import -alias yourdomain -keystore rsa-keystore \
    -file your-certificate.cer
-----

Where +yourdomain+ is a domain name for which this certificate has been generated. If you need support for multiple virtual domains you have to import certificate for each domain separately and assign proper alias to each certificate. If you have just one domain or for some reason you want to use one certificate use +default+ as an alias for all domains.

It's also good to import root CA certificate to this keystore. //You must find it on CA website.

[source,sh]
-----
keytool -import -keystore rsa-keystore -file rootCA.cer
-----

It may also generate certreq using +openssl+ for use in other services like WWW. In such a case you may have your private key and certificate in separate files. Let's say private key is in ssl.key file and certificate is in +ssl.crt+ file. To merge them into a single file together use following command:

[source,sh]
-----
openssl pkcs12 -export -inkey ssl.key -in ssl.crt \
    -out mycert.pfx -name "default"
-----

Now you can load certificate with a private key to your keystore:

[source,sh]
-----
keytool -importkeystore -srckeystore mycert.pfx \
    -srcstoretype pkcs12 -destkeystore rsa-keystore \
    -srcalias default -destalias yourdomain \
    -destkeypass your_keystore_pass
-----

*Note!* _Please note -destkeypass parametr. Your keys password must be the same as keystore password. Otherwise it won't work._

Now you have to copy file +rsa-keystore+ to directory +certs/+ in your tigase server installation. The file could also be installed in different location but then corrections to the config file are required. Refer to configuration documentation for details.

Finally, don't forget to modify tigase server configuration file and set proper password for your keystore.
