[[setupTigaseServer]]
= Tigase Server Network Instructions
:author: Daniel Wisnewski <daniel@mail.tigase.org>
:version: v1.0, May 2016: Reformatted for AsciiDoc.
:date: 2016-05-13 10:30

:toc:
:numbered:
:website: http://tigase.net

One you have installed Tigase XMPP Server on a machine, you're going to want to use it.  If you are just using for local communications on a network behind a router, you're all set.  Enjoy and use!

However, if you want to have people from other computers outside your network connect to your server, you're going to have to go through a few more steps to show your server out to the public.

NOTE: This guide is merely a recommendation of how to get a local server to be open to incoming communications.  Any time you open ports, or take other security measures you risk compromising your network security.  These are only recommendations, and may not be appropriate for all installations.  Please consult your IT Security expert for securing your own installation.

XMPP, being a decentralized communication method, relies on proper DNS records to figure out where and how an XMPP server is setup.  Operating an XMPP Server will require you to properly setup DNS routing so not only can clients connect to you, but if you decide to run a federated server and enable server to server communication, you will need to do the same.  If you already have a DNS server already, you should have little issue adding these records.
If you do not have a DNS setup pointing to your server, you may use a free dynamic name service such as dynu.com.

== A Records
You will not be able to use an IP Address or a CNAME record to setup an XMPP Server.  While it's not required, an A record can provide some other benefits such serving as a backup in case the SRV record is not configured right.

== SRV Records
You will need to set SRV records both for client-to-server (c2s) communication and, if you plan to use it, server to server (s2s) communication.  We recommend both records are entered for every server as some resources or clients will check for both records.
For this example we will use tigase.org is our domain, and xmpp as the xmpp server subdomain.

SRV records have the following form:

_service._protocol.name. TTL class SRV Priority weight port target.

The key is as follows:

* *service*: is the symbolic name of the desired service, in this case it would be _xmpp-client_ or _xmpp-server_.
* *protocol*: is the transport protocol, either TCP or UDP, XMPP traffic will take place over _TCP_.
* *name*: the domain name where the server resides, in this case _tigase.org_.
* *TTL*: a numeric value for DNS time to live in milliseconds, by default use _86400_.
* *class*: DNS class field, this is always _IN_.
* *priority*: the priority of the target host with lower numbers being higher priority.  Since we are not setting up multiple SRV records, we can use _0_.
* *weight*: the relative weight for records with the same priority. We can use _5_.
* *port*: the specific TCP or UDP port where the service can be found. In this case it will be _5222_ or _5269_.
* *target*: the hostname of the machine providing the service, here we will use _xmpp.tigase.org_.

For our example server, the SRV records will then look like this:

*_xmpp-client._TCP.tigase.org 86400 IN SRV 0 5 5222 xmpp.tigase.org*

*_xmpp-server._TCP.tigase.org 86400 IN SRV 0 5 5269 xmpp.tigase.org*

=== Tigase and Vhosts
If you are running multiple vhosts or subdomains that you wish to separate, you will need another record.  In this case an A record will be all you need if you are using default ports.  If you are using custom ports, you will need to have a new SRV record for each subdomain.

== Port Forwarding
Once your server is setup, you may need to open at least two ports.  XMPP communication handling and SRV records occur on two ports; 5222 and 5269.  SRV records may result in an error if these ports cannot be contacted by the SRV records service, and you will be unable to connect from outside your network.
Both ports should be setup to use TCP only.  Remember, if you set custom ports for your servers communications, you may need to forward them as well.

. If you are using TURN or STUN, you will need to forward 3478 under TCP and UDP.
. If you are planning to use STUN or TURN over TLS, forward 5349 under TCP.

If you have a cell phone on a separate network with an XMPP client, you can now try to login to test the server.  If that is not handy, you can use an online tool to check proper DNS records such as kingant's: link:https://kingant.net/check_xmpp_dns/[https://kingant.net/check_xmpp_dns/] and it will tell you if anything is missing.
Other ports you may need to forward to the server are:
- 5222
- 5223
- 5269
- 5277
- 5280
- 5290
- 8080
