//[[loadComponent]]
Configuring the Tigase Server to Load a Component
=================================================
Artur Hefczyc <artur.hefczyc@tigase.net>
v2.0, June 2014: Reformatted for AsciiDoc.
:toc:
:numbered:
:website: http://tigase.net
:Date: 2010-04-06 21:18

A detailed description of all the configuration options is in the ////<<initPropertiesGuide,////init.properties guide where you can also find information described below and much more. Purpose of this document however is to give you a quite and brief information how to load a component into the Tigase server without need to dig through all the details.

I will show how to load 2 components into the Tigase server using configuration in the init.properties file: link:https://projects.tigase.org/projects/tigase-muc[MUC] and link:https://projects.tigase.org/projects/tigase-pubsub[PubSub]. Please remember, every time you change something in the *init.properties* file you have to remove the XML configuration file in order to force the server to regenerate the main configuration which is stored in XML file. 

The first thing you need is the component implementation. Component implementation is a class or set of classes extending link:http://projects.tigase.org/server/trac/browser/trunk/src/main/java/tigase/server/AbstractMessageReceiver.java[tigase.server.AbstractMessageReceiver]. What you need to do is just putting the jar file in the +libs/+ directory in the Tigase server installation. Then the Tigase server will find all classes automatically at the startup time. 

Next step is to tell the server what components to load, how to name them and optionally give some extra parameters. To do so please open the init.properties file you use in your installation. It might be init-mysql.properties or init-pgsql.properties or even your own properties file.

Let's say you want to add just PubSub for now. All you need to do is adding just 2 lines to the properties file: 

[source,bash]
-------------------------------------
--comp-name-1=pubsub
--comp-class-1=tigase.pubsub.PubSubComponent
-------------------------------------

They mean: the first component name is 'pubsub' and the main class for this component is: 'tigase.pubsub.PubSubClusterComponent'. It doesn't really matter what the component name is the only requirement is that it must be unique among other components names. It does also help to give it a name which means something thus 'pubsub' is a good name for a 'PubSub' component but it would be a bad name for the 'MUC' component.

We can of course add more components even PubSub components to the same server. Each of them would need to have a different name then. For example:

[source,bash]
-------------------------------------
--comp-name-2=pubsub-priv
--comp-class-2=tigase.pubsub.PubSubComponent
-------------------------------------

Which is needed in really rare cases. 

Normally, however we want to load few different components like PubSub, MUC, MSN Transport and so on.... Therefore instead of the above second PubSub we can load the MUC component: 

[source,bash]
-------------------------------------
--comp-name-2=muc
--comp-class-2=tigase.muc.MUCComponent
-------------------------------------
Again! Don't forget to remove your XML config file before restarting the server.

