[[databasemgnt]]
Database Management
===================
:author: daniel wisnewski
:version: v1.0 July 2015
:date: 2015-07-16 12:49

:website: http://tigase.net

Tigase is coded to perform with multiple database types and numbers.
Owing to it's versatile nature, there are some tools and procedures that may be of use to certain administrators.

Recommended database versions
-----------------------------
As of v7.2.0-SNAPSHOT here are the minimum and recommended versions of databases for use with Tigase:


[width="100%",frame="topbot",options="header"]
|=================================
|Database   |Recommended Version  |Minimum Version  |Additional Information
|DerbyDB    |10.12.1.1            |10.12.1.1        |Included with Tigase XMPP Server
|MySQL      |5.7                  |5.6              |
|SQLServer  |2014                 |2012             |2012 needed so we can count use fetch-offset pagination feature.
|PostgreSQL |9.5                  |9.4              |New UA schema requires at least 9.4
|MongoDB    |3.2                  |3.0              |
|MariaDB    |?                    |10.0.12          |Basic features works with 10.0.12-MariaDB Homebrew, but is not fully tested.
|=================================

Although Tigase may support other versions of databases, these are the ones we are most familiar with in offering support and advice.  Use of databases outside these guidelines may result in unforeseen errors.

xref:databasePreperation[Database Preparation]
----------------------------------------------
Preparing new databases in case installer setup is not an option.

xref:hashedPasswords[Hashed Passwords in User Database]
-------------------------------------------------------
Providing more secure password storage.

xref:multidb[Multiple Databases in Tigase]
------------------------------------------
Options for using multiple databases for different purposes in Tigase.

xref:dbImportingData[Importing User Data]
-----------------------------------------
Tips to move data repositories from one to another database.

xref:existingData[Import Existing Database]
-------------------------------------------
This section has some depreciated information, however it may be handy to upgrade, or manually connect databases.

xref:oldVerSchemas[Old Version Schemas and Updates]
---------------------------------------------------
Contains our old Schema updates, if you have an old installation of Tigase and want to move to a more current version, see the guides revelant to you.
