//[[shortConfigurationGuide2]]
Short Configuration Guide
=========================
Artur Hefczyc <artur.hefczyc@tigase.net>
v2.0, June 2014: Reformatted for AsciiDoc.
:toc:
:numbered:
:website: http://tigase.net
:Date: 2010-04-06 21:16

Options you most likely have to change at deployment time are:

. *Admin* *accounts* -  account names where all admin messages are sent.
. *Hostnames* -  real and virtual hostnames your server has to serve for.
. *Logs* - setting related to log file location and how much information should be logged there.

Please let me know if you think more options should be described here.

*Changing configuration using command line tool.*

Detailed description of configuration management tool in on project site on the: ////<<configurationManagement2,////Configuration management tool page.

Admin Accounts
--------------

This is the most likely thing to change after you install server and generate default configuration. Actually it is also the easiest option to customize.

And yes, you can just remove entry with admin account: +"admin@localhost"+ unless you really want to keep it. Be aware though all system messages will be sent to *ALL* admin accounts.

Well, if the account does not exists the message is discarded and a warning is be printed in log file. Again, read it again, the previous sentence...

It means that the admin account has to be also created in normal way on the Jabber server. Just register it using your Jabber client. The admin accounts setting works just as a forward instruction. So as a result all system and admin messages are forwarded to all admin accounts if they exist.

Obviously you can have as many admin accounts as you like:

[source,bash]
-------------------------------------
session_1/admins = frank@jabber.example.com, lucy@jabber.example.com,
    mark@jabber.example.com, brenda@jabber.example.com, luck@jabber.example.com
-------------------------------------

Now, how to do it. First things is to find current settings. To see what are current admin accounts execute the command:

[source,sh]
-------------------------------------
./bin/config.sh -c etc/tigase-server.xml -print -key session_1/admins
-------------------------------------

As a result you can see something like this:

[source,bash]
-------------------------------------
session_1/admins = admin@yourhost, admin@localhost
-------------------------------------

As you could read in configuration management too guide '-add' command adds new entries to the list, '-set' command removes old values and sets new one.

As we want to create new admins list for the installation first command would be '-set' command. Let's say we want set +jack@yourhost+ as your first admin account:

[source,sh]
-------------------------------------
./bin/config.sh -c etc/tigase-server.xml -print -key session_1/admins -set -value "jack@yourhost"
-------------------------------------

As a result program prints new setting:

[source,bash]
-------------------------------------
session_1/admins = jack@yourhost
-------------------------------------

All old accounts have been replaced with new account. Now if you wich to add next admin account +john@yourhost+ to the list execute slightly modified command (Note - '-add' instead of '-set'):

[source,sh]
-------------------------------------
./bin/config.sh -c etc/tigase-server.xml -print -key session_1/admins -add -value "john@yourhost"
-------------------------------------

And result:

[source,bash]
-------------------------------------
session_1/admins = jack@yourhost, john@yourhost
-------------------------------------

And... this is it. You can add more admin accounts the same way.
 
Hostnames
---------

This one might be a little bit more tricky than previous as *hostnames* setting has to be changed in a few places. Don't ask why now as this is the "_Short configuration guide_", you remember. Here we focus on *how* not on *why*.

The best way to find all places where hostnames should be changes execute following command:

[source,sh]
-------------------------------------
./bin/config.sh -c etc/tigase-server.xml -print | grep hostnames
-------------------------------------

As a result you can see something like this:

[source,bash]
-------------------------------------
tigase-xmpp-server/hostnames = yourhost, localhost
client_1/hostnames = yourhost, localhost
server_1/hostnames = yourhost, localhost
session_1/hostnames = yourhost, localhost
-------------------------------------

It may also look:

[source,bash]
-------------------------------------
tigase-xmpp-server/hostnames = localhost
client_1/hostnames = localhost
server_1/hostnames = localhost
session_1/hostnames = localhost
-------------------------------------

Depending how successful was mechanism for automatic hostname detection. It of course does not depends on your luck. It depends on network configuration on your server.

The first form is more useful as it includes also hostname recognized in network environment. If it is correct then you can just leave it as it is. If it is incorrect you have to change it. Please remember, if you want your server to be able to communicate with other _Jabber/XMPP_ servers the hostname you put there must resolve in DNS to your Jabber server machine IP address. In other words. If you try to connect from the Internet to machine with this hostname the connection should reach your Jabber server.

And remember your Jabber server users' JIDs (_Jabber IDs_) can include only those hostnames which are included in the configuration. So for our case you can use only _JIDs_: +"user2@your.hostname.com",+ +"user1@your.hostname.com"+ and so on.

If you server have more Internet addresses (virtual domains) assigned to it your Jabber server can use them all. So your configuration may look ike:

[source,bash]
-------------------------------------
tigase-xmpp-server/hostnames = yourhost, localhost, your.hostname.com, clien1.hostname.com
client_1/hostnames = yourhost, localhost, your.hostname.com, clien1.hostname.com
server_1/hostnames = yourhost, localhost, your.hostname.com, clien1.hostname.com
session_1/hostnames = yourhost, localhost, your.hostname.com, clien1.hostname.com
-------------------------------------

In such case users' _JIDs_ on your Jabber server may include any of defined above domains like: "user1@your.hostname.com", _"user1@clien1.hostname.com",_ _"user1@yourhost"._ Each of these 3 sample _JIDs_ refer to different user account.

Your server will accept connections only for domains defined in configuration file.

In majority cases it does not matter whether you leave *"localhost"* or remove it. It is sometimes better to leave it though. So if you are not sure if you can remove it in your environment just leave it as is.

Now it is a time to change hostnames. Assuming default configuration is not what you need than first you have to set all these settings to accept connections from +localhost+:

[source,sh]
-------------------------------------
./bin/config.sh -c etc/tigase-server.xml -print -key tigase-xmpp-server/hostnames -value localhost -set 
./bin/config.sh -c etc/tigase-server.xml -print -key client_1/hostnames -value localhost -set
./bin/config.sh -c etc/tigase-server.xml -print -key server_1/hostnames -value localhost -set
./bin/config.sh -c etc/tigase-server.xml -print -key session_1/hostnames -value localhost -set
-------------------------------------

Now we can add you "real" host name, let's say it is yourhost:

[source,sh]
-------------------------------------
./bin/config.sh -c etc/tigase-server.xml -print -key tigase-xmpp-server/hostnames -value yourhost -add
./bin/config.sh -c etc/tigase-server.xml -print -key client_1/hostnames -value yourhost -add
./bin/config.sh -c etc/tigase-server.xml -print -key server_1/hostnames -value yourhost -add
./bin/config.sh -c etc/tigase-server.xml -print -key session_1/hostnames -value yourhost -add
-------------------------------------

The same way you can add more virtual hosts to you configuration.

