//[[genericdatabasePreperation]]
Database Preparation
====================
Artur Hefczyc <artur.hefczyc@tigase.net>
v2.0, June 2014: Reformatted for AsciiDoc.
:toc:
:numbered:
:website: http://tigase.net
:Date: 2012-07-15 06:42

Tigase uses generally the same DB schema and the same set of stored procedures and functions on every database. However, the schema creation scripts and code for stored procedures is different for each database. Therefore the manual process to prepare database is different for each of them.

Of course the simplest and easiest way to prepare database is to use Tigase installer which automates the whole process. Sometimes it is not possible however. Here we provide a set of guides, describing initialization and preparation process for each supported database.

- ////<<prepareMysql,////Prepare the MySQL Database for the Tigase Server
- ////<<hashedPasswords,////Hashed User Passwords in Database
- ////<<prepareDerby,////Prepare the Derby Database for the Tigase Server
- ////<<prepareMssql,////Prepare the MS SQL Server Database for the Tigase Server
- ////<<preparePostgresql,////Prepare the PostgreSQL Database for the Tigase Server

