[[tigase710]]
Tigase v7.1.0 announcement
==========================
:author: Daniel Wisnewski
:date: 2015-25-08 22:09


Introducing Tigase v7.1.0!  We have been working hard to improve and implement new features to the Tigase Sever program to give you a more secure, leaner, and better working XMPP server.

We have a few new features, components, and lots of fixes to share.

:toc:

Major Changes
-------------
Tigase has undergone a few major changes to our code and structure. To continue to use Tigase, a few changes may be needed to be made to your systems.  Please see them below:

New JDK v8 required
~~~~~~~~~~~~~~~~~~~
As Oracle has dropped support for version 7 of it's Java runtime environment and developer kit, we have moved to version 8 of the JDK.  Furthermore, some new features and fixes for Tigase Server now require the use of JDK v8 or later. Please upgrade your Java packages from link:http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[this link].

Changes to Datbase Schema
~~~~~~~~~~~~~~~~~~~~~~~~~
Database Schema has changed to introduce primary keys in tig_nodes and tig_pairs tables, improving database performance.  As a result, the schema for your database will need to be upgraded if you are not starting with a fresh database.
Please see the xref:tigaseServer71[Schema Upgrade] section for instructions on how to prepare and upgrade your database.  *This will affect all users using v7.1.0 b4129 and later.*

Changes to Pubsub Schema
~~~~~~~~~~~~~~~~~~~~~~~~
The PubSub Schema has been streamlined for better resource use, this change affects all users of Tigase.
To prepare your database for the new schema, first be sure to create a backup!  Then apply the appropriate pubsub schema to your MySQL and it will add the new storage procedure.
Details on how to accomplish this are found xref:pubSub71[in the schema upgrade guide].

Presence Plugin Split
~~~~~~~~~~~~~~~~~~~~~
The plugin handling all presence processing has been split from one plugin (Presence.java) into separate plugins:
- PresenceAbstract.java handles most common presence-related methods, and is also used by the following two plugins.
- PresenceSubscription.java to handle subscription presence processing like for roster updates.
- PresenceState.java to handle initial presences from new logins.


New Features & Components
-------------------------

New HTTP API
~~~~~~~~~~~~
Tigase now features an HTTP API that not only allows web client chat, but administrators can change settings, manage users, and even write and run scripts all from the comfort of a browser window.   Furthermore, commands can be passed through this interface using REST to create and run custom scripts and commands.
We plan on expanding on the look and feel of this interface as time goes on, but in the meantime enjoy the real-time XMPP experience now with a user-friendly GUI.

New Admin HTTP interface
~~~~~~~~~~~~~~~~~~~~~~~~
Tigase now comes with its own build-in web XMPP client!  It can be accessed from http://yourhost.com:8080/ui/. For more details, see the Admin UI guide.

Added support for XEP-0334
~~~~~~~~~~~~~~~~~~~~~~~~~~
Added support to store offline messages for messages without body content. See link:http://xmpp.org/extensions/xep-0334.html[XEP-0334] for protocol details.
Support also added to set a list of paths and xmlns to trigger and place storage of offline messages using the following settings in init.properties:
-----
sess-man/plugins-conf/amp/msg-store-offline-paths[s]=/message/received[urn:xmpp:receipts],/message/store-offline
-----

Kernel Bean Configurator has been Improved
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Added aliases for bean properties to allow for a 'high level' of configuration.
Instead of using
-----
component/bean-name/property=value
-----
The following easier to use method will work
-----
component/property=value
-----

Maximum users setting for MUC
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Administrators can now set that maximum number of users allowed on specific MUCs.
See xref:mucRoomConfig[MUC Room Configuration]

HTTP Rest API Support
~~~~~~~~~~~~~~~~~~~~~~
Tigase now supports REST commands via HTTP, they can be sent from ad-hoc commands, a web interface, or other REST tools. See xref:tigase_http_api[documentation] for more.

Empty Nicknames
~~~~~~~~~~~~~~~
Tigase can now support users with empty nicknames so long as the following code is in init.properties.
------
sess-man/plugins-conf/jabber\:iq\:roster/empty_name_enabled=true
------

Offline Message Limits
~~~~~~~~~~~~~~~~~~~~~~
Tigase now has support to enable and change Offline Message Limits as handled by AMP. xref:offlineMessageLimits[Documentation here].

Offline Message Sink
~~~~~~~~~~~~~~~~~~~~
A new way to store offline messages has been implemented, it may not replace standard offline messages, but can be used in other ways.
xref:offlineMessageSink[Documentation here]

Adding Components to trusted list
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Components can now be added to trusted list and will be shared with all clustered servers.
link:https://projects.tigase.org/issues/3244[#3244]

Tigase Mailer Extension now Included
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Tigase mailer extension is now included in distributions of Tigase server. This extension enables the monitor component to deliver E-mails to and from specified e-mail addresses when monitor are triggered.  For more information see xref:monitorMailer[monitor mailer section].

EventBus implemented
~~~~~~~~~~~~~~~~~~~~
Tigase now has a simple PubSub component called EventBus to report tasks and triggers.  More details are available xref:eventBus[Here].

XEP-0191 Blocking Command Support added
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Blocking Command support has been added to Tigase, all functions of link:http://xmpp.org/extensnions/xep-0191/html[XEP-0191] should be implemented.  See xref:blockingCommand[Admin Guide] for details.

JVM Default configuration updated
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Default tigase.conf file has been updated with the following change in JVM options:
-----
PRODUCTION_HEAP_SETTINGS=" -Xms5G -Xmx5G " # heap memory settings must be adjusted on per deployment-base!
JAVA_OPTIONS="${GC} ${EX} ${ENC} ${DRV} ${JMX_REMOTE_IP} -server ${PRODUCTION_HEAP_SETTINGS} -XX:MaxDirectMemorySize=128m "
-----
As the comment says, we recommend adjusting the heap memory settings for your specific installations.
link:https://projects.tigase.org/issues/3567[#3567]

New Rest API added to obtain a JID login time
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+GetUserInfo+ command has been expanded to obtain user login and logout times in addition to standard information. To obtain the information, send a POST request to http://xmpp.domain.net:8080/rest/adhoc/sess-man@xmpp.domain.net?api-key=test-api-key with the following:
[source,xml]
-----
<command>
  <node>get-user-info</node>
  <fields>
    <item>
      <var>accountjid</var>
      <value>user@xmpp.domain.net</value>
    </item>
    <item>
      <var>Show connected resources in table</var>
      <value>true</value>
    </item>
  </fields>
</command>
-----

New init.properties property
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+--vhost-disable-dns-check=true+
Disables DNS checking for vhosts when changed or edited.
When new vhosts are created, Tigase will automatically check for SRV records and proper DNS settings for the new vhosts to ensure connectivity for outside users, however if these validations fail, you will be unable to save those changes. This setting allows you to bypass that checking.

Connection Watchdog
~~~~~~~~~~~~~~~~~~~
A watchdog property is now available to monitor stale connections and sever them before they become a problem.  More details xref:watchdog[here].

Offline Message Receipts Storage now Configurable
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Admins may now configure Offline Message Receipts Storage to specify filters and controls as to what they want stored in offline messages. See xref:offlineMessageReceipts[more details here].

Account Registration Limits
~~~~~~~~~~~~~~~~~~~~~~~~~~~
In order to protect Tigase servers from DOS attacks, a limit on number of account registrations per second has been implemented.  This may be configured by adding the following line in the init.properties file:
-----
sess-man/plugins-conf/jabber\:iq\:register/registrations-per-second=10
-----
This setting allows for 10 registrations from a single IP per second.  If the limit exceeds that, a NOT_ALLOWED error will be returned.

Cluster Connections Improved
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Cluster commands now operate at CLUSTER priority, giving the packets higher status than HIGH which otherwise has caused issues during massive disconnects.
New Configuration options come with this change.  The first being able to change the number of connections for CLUSTER packets using the following init.property setting:
-----
cl-comp/cluster-sys-connections-per-node[I]=2
-----
Also a new class which implements the a new connection selection interface, but uses the old mechanism where any connection can send any command.
-----
cl-comp/connection-selector=tigase.cluster.ClusterConnectionSelectorOld
-----

Cluster Connections Testing Implemented
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Watchdog has now been added to test cluster connections by default.  Watchdog sends an XMPP ping to all cluster connections every 30 seconds and checks to see if a ping response has been received in the last 3 minutes. If not, the cluster connection will be dropped automatically. Global watchdog settings will not impact cluster testing feature.

Cluster Map implemented
~~~~~~~~~~~~~~~~~~~~~~~
Tigase can now generate cluster maps through a new API.  See the development guide for a description of the API.

Message Archive expanded to include non-body elements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Message Archive can now be configured to store messages that may not have body element, or other message types using the following line from init.properties:
-----
sess-man/plugins-conf/unified-archive/msg-archive-paths[s]=/message/body,/message/subject
-----
Where above will set the archive to store messages with <body/> or <subject/> elements.

New Ability to Purge Data from Unified Archive
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This feature allows for automatic removal of entries older than a configured number of days from the Unified Archive. It is designed to clean up database and keep its size within reasonable boundaries.

There are 4 settings available for this feature:
To enable the feature:
+unified-archive/remove-expired-messages[B]=true+

This setting changes the initial delay after the server is started to begin removing old entries.  In other words, UA purging will not take place until the specified time after the server starts.  Default setting is PT1H, or one hour.
+unified-archive/remove-expired-messages-delay=PT2H+

This setting sets how long UA purging will wait between passes to check for and remove old entries. Default setting is P1D which is once a day.
+unified-archive/remove-expired-messages-period=PT2D+

Configuration of number of days in VHost
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
VHost holds a setting that determines how long a message needs to be in archive for it to be considered old and removed.  This can be set independently per Vhost.  This setting can be modified by either using the HTTP admin, or the update item execution in adhoc command.

Command-line utility
Sets after how many days message should be removed - by default we use 24 hours. So if entry is older than 24 hours then it will be removed, ie. entry from yesterday from 10:11 will be removed after 10:11 after next execution of purge.
This configuration is done by execution of Update item configuration adhoc command of vhost-man component, where you should select domain for which messages should be removed and then in field XEP-0136 - retention type select value Number of days and in field XEP-0136 - retention period (in days) enter number of days after which events should be removed from UA.

In adhoc select domain for which messages should be removed and then in field XEP-0136 - retention type select value Number of days and in field XEP-0136 - retention period (in days) enter number of days after which events should be removed from UA.

In HTTP UI select Other, then Update Item Configuration (Vhost-man), select the domain, and from there you can set XEP-0136 retention type, and set number of days at XEP-0136 retention period (in days).

Value of +remove-expired-messages-delay+ and +remove-expired-messages-period+ is in format described at Duration.parse() in Java documentation.

*NOTE* that these commands are also compatible with freely available tigase +message-archive+ component, just replace +unified+ with +message+.

New Documentation Structure
~~~~~~~~~~~~~~~~~~~~~~~~~~~
There has been a lot of changes and fixes to our documentation over the last few months. If you have links to any of our documentation, please update them as the filenames may have changed.

Full XML of last available presence may be saved to repository
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A more detailed last available presence can now be made from some configuration changes, along with a timestamp before the entire presence stanza is saved to the repository.  More information is available xref:storeFullXMLLastPresence[here].

New Minor Features & Behavior Changes
-------------------------------------
- Old monitor component depreciated and turned off.
- JTDS MS SQL Server driver updated to v1.3.1.
- tigase-utils and tigase-xmltools are now included in tigase-server builds.
- Tigase Kernal has been updated and improved.
- javadoc is no longer generated by installer as files are already included in distributions.
- link:https://projects.tigase.org/issues/163[#163] link:http://xmpp.org/extensions/xep-0012.html[XEP-0012] User +LastActivity+ implemented
- link:https://projects.tigase.org/issues/593[#593] link:http://xmpp.org/extensions/xep-0202.html[XEP-0202 Entity Time] has been implemented.
- #811 Plugin API extended allowing more XML parameters to be considered for processing.
- link:https://projects.tigase.org/issues/813[#813] Default number of connections between cluster nodes set at 5, default number of connections for CLUSTER level traffic set to 2.
- link:https://projects.tigase.org/issues/1436[#1436] +ClusterConnectionManager+ now sends ping packets every 30 seconds to check status of live cluster connections.
- link:https://projects.tigase.org/issues/1449[#1449] Monitoring can now be run in OSGI mode.
- link:https://projects.tigase.org/issues/1601[#1601] XMPPPresenceUpdateProcessorIFC interface has been removed and replaced with eventbus with dedicated threadpool.
- link:https://projects.tigase.org/issues/2426[#2426] Support for link:http://xmpp.org/extensions/xep-0334.html[XEP-0334] has been added.
- link:https://projects.tigase.org/issues/2561[#2561] & link:https://projects.tigase.org/issues/85[#85] Offline messages now consider sessions without presence & resources negative priority in delivery logic.
- link:https://projects.tigase.org/issues/2596[#2596] Delivery errors are no longer run through preprocessors.
- link:https://projects.tigase.org/issues/2823[#2823] +staticStr+ element method now implemented.
- link:https://projects.tigase.org/issues/2835[#2835] Allowing of +setPermissions+ on incoming packets before they are processed by plugins.
- link:https://projects.tigase.org/issues/2903[#2903] +see-other-host+ has new option to make it configurable on a per vhost basis.
- link:https://projects.tigase.org/issues/3034[#3034] Improved handling of data types and primitives within Tigase.
- link:https://projects.tigase.org/issues/3180[#3180] Protected access to JDBC repository now enabled.
- link:https://projects.tigase.org/issues/3230[#3230] Verification added to check against CUSTOM domain rules when submitted.
- #3258 Retrieval of PubSub/PEP based avatars using REST API now supported. xref:avatarRetrievalRequests[Command URLs here].
- #3282 VCard4 support added along with VCardTemp compatibility and integration.
- link:https://projects.tigase.org/issues/3285[#3285] Stream Management changed to fully support XEP-0203.
- link:https://projects.tigase.org/issues/3330[#3330] Error for adding users already in db now returns Error 409 with +User exists+.
- #3364 Clustering support has been re-factored to remove duplicate +nodeConnected+ and +nodeDisconnected+ methods.
- #3463 +offline-roster-last-seen+ feature as a part of presence probe is now disabled by default.
- link:https://projects.tigase.org/issues/3511[#3511] Stream closing mechanism in SessionManager, new STREAM_CLOSED command has been added to organize shutdown of XMPP streams.
- #3609 Added new configuration option for BOSH to disable hostname attribute. xref:tip_1_bosh_in_cluster_mode_without_load_balancer[Details here].


Fixes
-----
- link:https://projects.tigase.org/issues/8[#8] XML parser no longer passes malformed XML statements to server.

- link:https://projects.tigase.org/issues/1396[#1396] & link:https://projects.tigase.org/issues/663[#663] User roster behaves correctly. Tigase now waits for user authorization before users are added to a Roster.

- link:https://projects.tigase.org/issues/1488[#1488] NPE in ad-hoc for managing external components fixed.

- link:https://projects.tigase.org/issues/1602[#1602] Minor optimization in MessageCarbons with new functions added to XMPPResourceConnection.

- link:https://projects.tigase.org/issues/2003[#2003] Fixed bug with C2S streams where server would not always overwrite from attribute with full JID in subcription-related presence stanzas.

- link:https://projects.tigase.org/issues/2118[#2118] Username modification bugfix. Tigase now returns "" for blank usernames instead of string after a username has been made blank.

- link:https://projects.tigase.org/issues/2859[#2859] & link:https://projects.tigase.org/issues/2997[#2997] STARTTLS stream error on SSL sockets fixed.

- link:https://projects.tigase.org/issues/2860[#2860] Fixed issue with SSL socket client certificate not working.

- link:https://projects.tigase.org/issues/2877[#2877] Fixed issue in Message Carbons if message contains AMP payload.

- link:https://projects.tigase.org/issues/3034[#3034] Streamlined primitive and Object array handling.

- link:https://projects.tigase.org/issues/3067[#3067] Fixed Bug where if duplicate commands were sent to MS SQLServer a race condition would occur.

- link:https://projects.tigase.org/issues/3075[#3075] Fixed error when compiling Tigase in Red Hat Enterprise Linux v6.

- link:https://projects.tigase.org/issues/3080[#3080] --net-buff-high-throughput now parses integers properly. Setting no longer reverts to default when new values are set.

- link:https://projects.tigase.org/issues/3126[#3126] Calculation of percentage of heap memory used in Statistics now selects proper heap.

- link:https://projects.tigase.org/issues/3131[#3131] Fixed messages with AMP payload bound for plugins getting redirected to AMP for processing.

- link:https://projects.tigase.org/issues/3150[#3150] Default Log level changed for certain records. All log entries with skipping admin script now have log level +FINEST+ instead of +CONFIG+

- link:https://projects.tigase.org/issues/3158[#3158] Fixed issue with OSGi not reporting proper version, and PubSub errors in OSGi mode.

- link:https://projects.tigase.org/issues/3159[#3159] User Privacy lists now activate properly and does not wait for presence stanza to filter packets.

- link:https://projects.tigase.org/issues/3164[#3164] Fixed NPE in +StreamManagementIOProcessor+ when <a/> is processed after connection is closed.

- link:https://projects.tigase.org/issues/3166[#3166] NPE in SessionManager checking SSL null connections fixed.

- link:https://projects.tigase.org/issues/3181[#3181] S2S connection multiplexing now has consistent behavior.

- link:https://projects.tigase.org/issues/3194[#3194] Fixed issue with single long lasting HTTP connection blocking other HTTP requests. Default timeout set to 4 threads after 60 seconds.

- link:https://projects.tigase.org/issues/3200[#3200] Implemented a faster way to close stale connections using MS SQL server, reducing calm down time after large user disconnects.

- #3203 Correct presence status shows for contacts if authorization was accepted while user was offline.

- link:https://projects.tigase.org/issues/3223[#3223] +GetUserInfo+ ad-hoc command no longer omits information about local sessions when a remote session is active.

- #3226 Fixed NPE & argument type mismatch in Pubsub.

- link:https://projects.tigase.org/issues/3245[#3245] Fixed ClassCastException when Websocket is configured to use SSL.

- link:https://projects.tigase.org/issues/3249[#3249] JabberIQVersion plugin now returns proper client information when requested from self.

- link:https://projects.tigase.org/issues/3259[#3259] Websocket no longer loops when receiving stanzas between 32767 and 65535 bytes in size.

- link:https://projects.tigase.org/issues/3261[#3261] Fixed issue with duplicate disco#info responses.

- link:https://projects.tigase.org/issues/3274[#3274] NPE when removing roster nickname fixed.

- link:https://projects.tigase.org/issues/3307[#3307] Rosters are no longer re-saved when a user logs in and roster is read resulting in a performance boost.

- link:https://projects.tigase.org/issues/3328[#3328] Presence processing by PEP plugin optimized.

- link:https://projects.tigase.org/issues/3336[#3336] Fixed issues with reloading vhosts in trusted after configuration change.

- link:https://projects.tigase.org/issues/3337[#3337] tls-jdk-nss-bug-workaround-active is now disabled by default. This fix is disabled by default which may impact older OpenSSL versions that may no longer be supported.  You may enable this using an init.properties setting.

- #3341 IQ Packet processing changed for packets sent to bare JID in Cluster mode.

- link:https://projects.tigase.org/issues/3372[#3372] Fixed NPE when presence was rebroadcasted to users who did not exit server gracefully.

- link:https://projects.tigase.org/issues/3374[#3374] PubSub Schema changed to be more compatible with MS SQL.

- link:https://projects.tigase.org/issues/3375[#3375] Users removed VIA REST commands are now disconnected immediately.

- link:https://projects.tigase.org/issues/3386[#3386] Fixed AMP logic to avoid querying for (default) Privacy list if user does not exist.

- #3440 Fixed WebSocket error 12030 showing unexpectedly.

- link:https://projects.tigase.org/issues/3446[#3446] Fixed Installer configuring MUC incorrectly.

- #3449 Wrapper.conf updated with current library folder for windows Service wrapper.

- link:https://projects.tigase.org/issues/3453[#3453] Fixed NPE when using comparator when sorting messages.

- link:https://projects.tigase.org/issues/3495[#3495] Fixed messages being duplicated by message carbons.

- #3550 Fixed NPE in sess-man when trying to delete all user information using Pidgin or Psi.

- link:https://projects.tigase.org/issues/3559[#3559] Fixed Web admin UI not updating Cluster node when it id disconnected.

- link:http://projects.tigase.org/issues/3579[#3579] Fixed NPE in SimpleParser.

- #3598 Fixed error in removing users from blocked list.

- #3599 Fixed +FlexibleOfflineMessages+ not being delivered to connection due to lack of explicit connection addressing.

- #3612 Fixed issue when processing packets sent to full JID in cluster mode when user is connected to more than one cluster node at once.

- #3619 Fixed issue with non-presistent contacts being unable to be added to roster.

- #3649 Changed privacy list processing to always allow communication between XMPP connections with the same BareJID.

- link:https://projects.tigase.org/issues/3655[#3655] Increased max loop in infinity loop detection logic to 100000 in order to aid larger transfers.

- #3686 XHTML-IM parser has been fixed, restoring link:http://xmpp.org/extensions/xep-0071.html[XEP-0071] functionality.

- link:https://projects.tigase.org/issues/3688[#3688] Issues with Eventbus in cluster mode fixed.

- link:https://projects.tigase.org/issues/3689[#3689] Avoid using sender address when packets are returned from Cluster Manager using stream management.

- #3717 Support added to store messages without <body/> element if storage method other than <body/> is used. Support also added for JAXMPP to retrieve whole element from Message Archiving instead of only <body>.

- #3718 Removed +DISCONNECTING!+ debug stanza from AbstractWebSocketConnector.java that was causing NPE when user fails authentication in WebSocket.

- link:https://projects.tigase.org/issues/3775[#3775] Fixed +ThreadExceptionHandler+ error in Tigase mailer.

- link:https://projects.tigase.org/issues/3781[#3781] Fixed issue with sending C2S message "The user connection is no longer active".

- Patch added to fix ConcurrentModificationException in BlockingCommand plugin.

- Added missing classes to IzPack installer.

- Tigase.xml removed from documentation and default tigase.conf file.

- Logs function added to eventbus publisher operations.

- Fixed issue where attempts to delete empty MUC room would create and then destroy room.
