= How to Use Tigase Service

== This Article Describes How to use *tigase.im* Service for Instant Communications

You have to install and run a Jabber client application to use the service.

There are multiple domains available: tigase.im, sure.im, xmpp.cloud (and you can host your own domain as well)

=== Short instructions:

Usually you just need to enter the user name of the form: user@tigase.im. Your XMPP client should take care of all other things as our service doesn't need any special settings. If you don't have an account on tigase.im server yet just tick the option to register new account. That's it!

==== *Long Instructions:*
Good news is that there are many programs to choose from which allow you to communicate through our server. So you can pick up your favorite application or use an existing one that is compatible and start using our service.

All clients presented below support multiple accounts on Jabber servers. What this means is that you can have a few Jabber accounts on different Jabber servers and you can still use just one program to connect to all of them at the same time.


The https://xmpp.org/software/clients.html[full list of all known XMPP clients] is very long. You can obviously try them all but below is a selection which is recommended by the Tigase team. The selected programs might not be the best choice for you, but these programs have been tested and we can offer help with using them. Here is a list of recommended instant messaging clients:

- https://beagle.im/[Beagle.im] - macOS desktop client developed by Tigase team supporting all the latest and greatest features
- https://itunes.apple.com/us/app/tigase-messenger/id1153516838[Tigase Messenger for iOS] - lightweight, powerful XMPP client developed by Tigase, Inc. It provides an easy way to start using the XMPP Protocol (formerly known as Jabber) if you've never used it before. Veterans of the protocol will find many features here they are familiar with along with enhancements to reduce data use and extend battery life.
- https://play.google.com/store/apps/details?id=org.tigase.messenger.phone.pro[Tigase Messenger for Android] - mobile chat client to use with XMPP services and servers. The totally revamped v3.0 now has new features, a better design, and Google integration. Application supports any XMPP server, from free services like sure.im or Tigase.im, to a server you may host on your own.
- tigase.im[Tigase.im] - web-based client allowing to easily chat with friends independently of platform.
- http://psi-im.org/[Psi]
Pure Jabber client. Although it supports only Jabber network it is a very user friendly and comfortable program. It works on most popular operating systems like Linux, MS Windows, and Apple MacOS X.
- http://www.gajim.org/[Gajim]
This is another Jabber only client. Very user friendly and works on most of Linux distributions, FreeBSD, and MS Windows.
- http://www.pidgin.im/[Pidgin] (previously http://gaim.sourceforge.net/[Gaim])
This is not just a Jabber client. This type of application is called multicommunicator as apart from Jabber it supports many other instant messaging networks/protocols such as: AIM/ICQ, MSN, Yahoo, Gadu-Gadu, IRC, and a few others. So it is especially convenient if you have friends using other messaging networks. Pidgin works on most Linux distributions, and on MS Windows.
- http://kopete.kde.org/[Kopete]
This is a http://www.kde.org/[KDE] component and although it only works on Linux based system it also supports many of the most popular instant messaging protocols apart from Jabber like: AIM, Gadu-Gadu, ICQ, IRC, MSN, Yahoo.

Install the Jabber client of your choice and set up for a Tigase account: