create table tig_users (
	uid BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	user_id varchar(2049) NOT NULL,
	user_pw varchar(255) default NULL,
	last_login timestamp,
	last_logout timestamp,
	online_status int default 0,
	failed_logins int default 0,
	account_status int default 1
);

create unique index user_id on tig_users ( user_id );
create index user_pw on tig_users (user_pw);
create index last_login on tig_users (last_login);
create index last_logout on tig_users (last_logout);
create index account_status on tig_users (account_status);
create index online_status on tig_users (online_status);

create table tig_nodes (
	nid BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	parent_nid bigint,
	uid bigint NOT NULL references tig_users(uid),
	node varchar(255) NOT NULL
);
create unique index tnode on tig_nodes ( parent_nid, uid, node );
create index node on tig_nodes ( node );
create index nuid on tig_nodes (uid); -- The new index is a duplicate of an existing index
create index parent_nid on tig_nodes (parent_nid);

create table tig_pairs (
	nid bigint references tig_nodes(nid),
	uid bigint NOT NULL references tig_users(uid),
	pkey varchar(255) NOT NULL,
	pval long varchar
);
create index pkey on tig_pairs ( pkey ); -- The new index is a duplicate of an existing index
create index puid on tig_pairs (uid); -- The new index is a duplicate of an existing index
create index pnid on tig_pairs (nid);

create table short_news (
	snid BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	publishing_time timestamp default current timestamp,
	news_type varchar(10),
	author varchar(128) NOT NULL,
	subject varchar(128) NOT NULL,
	body varchar(1024) NOT NULL
);
create index publishing_time on short_news (publishing_time);
create index author on short_news (author);
create index news_type on short_news (news_type);

create table xmpp_stanza (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	stanza long varchar NOT NULL
);

CREATE function TigGetDBProperty(tkey varchar(255)) returns long varchar
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigGetDBProperty';

CREATE procedure TigPutDBProperty(tkey varchar(255), tval varchar(32672)) 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigPutDBProperty';

CREATE procedure TigInitdb() 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigInitdb';


CREATE procedure TigAddUser(userId varchar(2049), userPw varchar(255)) 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigAddUser';


CREATE procedure TigAddUserPlainPw(userId varchar(2049), userPw varchar(255)) 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigAddUserPlainPw';

CREATE procedure TigGetUserDBUid(userId varchar(2049)) 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigGetUserDBUid';

CREATE procedure TigRemoveUser(userId varchar(2049)) 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigRemoveUser';


CREATE procedure TigGetPassword(userId varchar(2049)) 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigGetPassword';


CREATE procedure TigUpdatePasswordPlainPw(userId varchar(2049), userPw varchar(255)) 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigUpdatePasswordPlainPw';

CREATE procedure TigUpdatePassword(userId varchar(2049), userPw varchar(255)) 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigUpdatePassword';


CREATE procedure TigOnlineUsers() 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigOnlineUsers';

CREATE procedure TigOfflineUsers() 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigOfflineUsers';

CREATE procedure TigAllUsers() 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigAllUsers';

CREATE procedure TigAllUsersCount() 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigAllUsersCount';


CREATE procedure TigUserLoginPlainPw(userId varchar(2049), userPw varchar(255)) 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigUserLoginPlainPw';

CREATE procedure TigUserLogin(userId varchar(2049), userPw varchar(255)) 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigUserLogin';

CREATE procedure TigUserLogout(userId varchar(2049)) 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigUserLogout';

CREATE procedure TigDisableAccount(userId varchar(2049)) 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigDisableAccount';

CREATE procedure TigEnableAccount(userId varchar(2049)) 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigEnableAccount';


CREATE procedure TigActiveAccounts() 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigActiveAccounts';

CREATE procedure TigDisabledAccounts() 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.tigDisabledAccounts';

CREATE procedure TigAddNode(parentNid bigint, uid bigint, node varchar(255)) 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	MODIFIES RESULT SETS 1
	EXTERNAL NAME 'tigase.db.derby.StoredProcedures.TigAddNode';
