[[loadComponent]]
= Configuring the Tigase Server to Load a Component

:author: Artur Hefczyc <artur.hefczyc@tigase.net>
:version: v2.1, June 2017: Reformatted for v7.2.0.
:date: 2010-04-06 21:18

:toc:
:numbered:
:website: http://tigase.net

A detailed description of all the configuration options is in the `init.properties` guide where you can also find information described below and much more. The purpose of this document is to give you a brief introduction on how to load a component into Tigase server without the need to dig through all the details.

I will show how to load 2 components into Tigase server using a configuration in the init.properties file: link:https://projects.tigase.org/projects/tigase-muc[MUC] and link:https://projects.tigase.org/projects/tigase-pubsub[PubSub].

The only step is to tell the server what components to load, how to name them and optionally give some extra parameters. To do so open the +init.properties+ file you use in your installation.

Let's say you want to just add PubSub for now. All you need to do is add the following to the properties file:

[source,dsl]
-----
pubsub (class: tigase.pubsub.PubSubComponent) {}
-----

Normally, this is not necessary since pubsub is loaded by default, however this is just an example of loading a class with the DSL format.

[source,dsl]
-----
'pubsub-priv' (class: tigase.pubsub.PubSubComponent) {}
-----
As you can see, we can customize the name of a component in the decleration, here we are using pubsub-priv.

Although this may be rare, it allows for wide compatibility and platform stability.

Normally, however we want to load few different components like PubSub, MUC, MSN Transport and so on.... Therefore instead of the above second PubSub we can load the MUC component:

[source,dsl]
-----
muc (class: tigase.muc.MUCComponent) {}
-----

Changes to the init.properties file will take effect upon server restart.
