[[tigaseExternalComponent]]
= External Component Configuration
:author: Artur Hefczyc <artur.hefczyc@tigase.net>
:version: v2.0, August 2017: Reformatted for v8.0.0.

:toc:
:numbered:
:website: http://tigase.net

As for all Tigase components you can load and configure external components via the `config.tdsl` file described in details in the xref:dslConfig[DSL configuration] section. This document describes how to load the component and set the initial configuration to accept or initiate connections for an external component.

First thing to do is to specify the component class and the component name which must be unique within the Tigase installation. The most commonly name used is `ext` and the class is `tigase.server.ext.ComponentProtocol` which does not need to be specified.

The following line in the `config.tdsl` will load the component during the server startup time:

[source,dsl]
-----
ext (class: tigase.server.ext.ComponentProtocol) {}
-----

While this would load the component, there are no additional configurations provided to the component would be practically useless.
It is necessary to configure the virtual host domains of the external component during run-time via ad-hoc commands to make use of this component.

You may additionally configure the xref:bindExtHostnames[`bind-ext-hostnames`] property.
