[[connectingTigaseToMysql]]
= Connecting the Tigase Server to MySQL Database
:author: Artur Hefczyc <artur.hefczyc@tigase.net>
:version: v2.1, June 2017: Reformatted for 7.2.0.
:date: 2010-04-06 21:16

:toc:
:numbered:
:website: http://tigase.net

Please before continuing reading of this manual have a look at the xref:prepareMysql[initial MySQL database setup]. It will help you with database preparation for connecting with Tigase server.

The easiest way to setup Tigase server for connecting with MySQL database is to use the xref:tigase3xconfiguration[configuration wizards] (configuration generators) which release you from manually editing the XML configuration file and allow you quickly regenerate the XML configuration file in case of problems.

The article describes an older way for using configuration generators which is a bit more difficult and doesn't work on Windows systems. The guide below describes a new way to use them which is simpler and can be applied to Windows systems as well. It is using the +init.properties+ file where you can put all your initial configuration parameters.

This guide describes MySQL database connection parameters.

This guide is actually very short as there are example configuration files which can be used and customized for your environment.

[source,dsl]
-----
dataSource {
    default () {
        uri = 'jdbc:mysql://localhost/tigasedb?user=tigase_user&password=mypass'
    }
}
userRepository {
    default () {}
}
authRepository {
    default () {}
}
-----

This is the basic setup for setting up an SQL repository for Tigase.  dataSource contains the uri for 'default' which is the mysql database.
MySQL connector requires connection string in the following format:
`jdbc:mysql://[hostname]/[database name]?user=[user name]&password=[user password]`

Edit the `init.properties` file for your environment.

Start the server using following command:

[source,sh]
-----
./scripts/tigase.sh start etc/tigase.conf
-----
