<?php
	/*
	 * Tigase Drupal Short News Module
	 * Copyright (C) 2004-2012 "Artur Hefczyc" <artur.hefczyc@tigase.org>
	 *
	 * This program is free software: you can redistribute it and/or modify
	 * it under the terms of the GNU Affero General Public License as published by
	 * the Free Software Foundation, either version 3 of the License.
	 *
	 * This program is distributed in the hope that it will be useful,
	 * but WITHOUT ANY WARRANTY; without even the implied warranty of
	 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	 * GNU Affero General Public License for more details.
	 *
	 * You should have received a copy of the GNU Affero General Public License
	 * along with this program. Look for COPYING file in the top folder.
	 * If not, see http://www.gnu.org/licenses/.
	 *
	 * $Rev:  $
	 * Last modified by $Author: $
	 * $Date:  $
	 */

	/**
	 * Display help and module information
	 * @param section which section of the site we're displaying help
	 * @return help text for section
	 */
function short_news_help($section='') {

	$output = '';

	switch ($section) {
	case "admin/modules#description":
		$output = t("Short news displaying from short_news table.");
		break;
	case "admin/help#short_news":
		$output = t("Short news displaying fro short_news table.") . "\n"
			. t(" This module displays N last short news found in 'short_news' table.");
		break;
	}

	return $output;
}

function short_news_perm() {
  return array('access short_news');
}

/**
* Generate list of last short news to display on page
* @param op the operation from the URL
* @param delta offset
* @returns block HTML
*/
function short_news_block($op='list', $delta=0) {
	// listing of blocks, such as on the admin/block page
	if ($op == "list") {
		$block[0]["info"] = t('Minis');
		return $block;
	} else if ($op == 'view') {
		$posts_type = variable_get('short_news_blocktype', 'minis');
		$max_posts = variable_get('short_news_blockdisp', 3);
    $result =
			db_query_range("SELECT snid, publishing_time, author, subject, body"
				. " FROM short_news WHERE news_type = '" . $posts_type. "'"
				. " ORDER BY publishing_time DESC"
				, 0, $max_posts);
    while ($news_post = db_fetch_object($result)) {
			if ($block_content == '') {
				$block_content .= '<div class="short-news">';
			}
			$block_content .= '<h6 class="title">' . $news_post->subject . '</h6>';
			$block_content .=	'<div class="body">' .	$news_post->body . '</div>';
			$block_content .= '<div class="author">'
				. $news_post->snid . ', '
				. str_ireplace('@', '//', $news_post->author)
				. ', '
				. format_date(strtotime($news_post->publishing_time), 'small')
				. '</div>';
    }
    // check to see if there was any content before setting up the block
    if ($block_content == '') {
      // no content from a week ago, return nothing.
      return;
    } else {
			$block_content .= '</div>';
		}
    // set up the block
    $block['subject'] = 'Minis from XMPP';
    $block['content'] = $block_content;
    return $block;
	}
}

/**
* Module configuration settings
* @return settings HTML or deny access
*/
function short_news_settings() {
  // only administrators can access this module
  if (!user_access("access administration pages")) {
    return t('you do not have rights to this resource.');
  }
	$form['short_news_blockdisp'] =
		array('#type' => 'textfield',
			'#title' => t('Number of posts to display in block'),
			'#default_value' => variable_get('short_news_blockdisp', 3),
			'#description' => t("The maximum number of posts to display in the block."),
			'#maxlength' => '2', '#size' => '2');
	$form['short_news_blocktype'] =
		array('#type' => 'textfield',
			'#title' => t('Posts type to display in block'),
			'#default_value' => variable_get('short_news_blocktype', 'minis'),
			'#description' => t("The type of posts to display in block: 'minis', 'shorts', 'techs', 'funs', ..."),
			'#maxlength' => '10', '#size' => '10');
  return $form;
}

