[[componentdevelpoment]]
Component Development
=====================
Artur Hefczyc <artur.hefczyc@tigase.net>
v2.0, June 2014: Reformatted for AsciiDoc.
:toc:
:numbered:
:website: http://tigase.net/
:Date: 2010-04-06 21:22

A component in the Tigase is an entity with own JID address. It can receive packets, can process them and can also generate packets.

An example of the best known components is MUC or PubSub. In the Tigase server, however, almost everything is actually a component: Session Manager, s2s connections manager, Message Router, etc.... Components are loaded based on the server configuration, new components can be loaded and activated at the server run-time. You can easily replace a component implementation and the only change to make is a class name in the configuration entry.

Creating components for the Tigase server is an essential part of the server development hence there is a lot of useful API and ready to use code available. This guide should help you to get familiar with the API and how to quickly and efficiently create own component implementations.

. Component implementation - Lesson 1 - Basics
. Component implementation - Lesson 2 - Configuration
. Component implementation - Lesson 3 - Multi-Threading
. Component implementation - Lesson 4 - Service Discovery
. Component implementation - Lesson 5 - Statistics
. Component implementation - Lesson 6 - Scripting Support
. Component implementation - Lesson 7 - Data Repository
. Component implementation - Lesson 8 - Startup Time
. Configuration API
. Packet Filtering in Component

