[[databasePreperation]]
= Database Preparation
:author: Artur Hefczyc <artur.hefczyc@tigase.net>
:author: v2.2, June 2014: Reformatted for v8.0.0.

Tigase uses generally the same database schema and the same set of stored procedures and functions on every database. However, the schema creation scripts and code for stored procedures is different for each database. Therefore the manual process to prepare database is different for each database system.

Starting with v8.0.0, most of the database tasks have been automated and can be called using simple text, or using interactive question and answer style. We **DO NOT RECOMMEND** going through manual operation, however we have kept manual activation of different databases to the Appendix.
If you are interested in how we manage and update our database schemas, you may visit the link:https://tigase.tech/projects/tigase-server/wiki/Schema_files_maintenance[Schema Maintenance] section of our Redmine installation for more detailed information.

- xref:dbSchemaLoader[The DBSchemaLoader Utility]
- xref:hashedPasswords[Hashed User Passwords in Database]
- xref:mongoDBSupport[Support for MongoDB]

Appendix entries

- xref:prepareMysql[Manual installtion for MySQL]
- xref:prepareDerby[Manual installtion for Derby]
- xref:prepareMssql[Manual installtion for SQLServer]
- xref:preparePostgresql[Manual installtion for PostGRESQL]
