[[tigase41virtualHosts]]
= Virtual Hosts in Tigase Server
:author: Artur Hefczyc <artur.hefczyc@tigase.net>
:version: v2.0, June 2014: Reformatted for AsciiDoc.
:date: 2010-04-06 21:18
:revision: v2.1

:toc:
:numbered:
:website: http://tigase.net

Tigase server supports multiple virtual hosts in a single server installation. This is supported via link:https://projects.tigase.org/projects/tigase-server/repository/changes/src/main/java/tigase/vhosts/VHostManagerIfc.java[VHostManager] - the new Tigase server component added recently to the implementation. Virtual hosts can be added or removed, enabled or disabled during runtime without restarting the service or disrupting normal operation.

This document describes how virtual hosts work in Tigase server and how to get the most out of this feature in your installation.

The xref:virtHosts['--virt-hosts'] property allows for configuration of virtual hosts in your init.properties file.

Virtual hosts may also be managed using ad-hoc commands, visit xref:ad-hocCommands[Specification for ad-hoc Commands Used to Manage Virtual Domains] for more information.

If you have components that may not be able to handle multiple vhosts or cluster mode, we have developed a virtual component solution as well, details in the xref:virtualComponents[Virtual Components for the Tigase Cluster] section.

You may also want to reference the Vhosts API for additonal information:
- xref:addManageDomain[API Description for Virtual Domains Management in Tigase Server].
