= How to Use Tigase Service
:author: Artur Hefczyc <artur.hefczyc@tigase.net>
:version: v2.0, June 2014: Reformatted for AsciiDoc.
:date: 2009-11-25 15:51
:revision: v2.1

:toc:
:numbered:
:website: http://tigase.net

== This Article Describes How to use *tigase.org* Service for Instant Communications
You have to install and run a Jabber client application to use the service.

=== Short instructions:

Usually you just need to enter the user name of the form: user@tigase.org. Your XMPP client should take care of all other things as our service doesn't need any special settings.  If you don't have an account on tigase.org server yet just tick the option to register new account. That's it!

=== Long Instructions:
The good news is that there are many programs to choose from which allow you to communicate through our server. So you can pick up your favorite application or use an existing one that is compatible and start using our service.

All clients presented below support multiple accounts on Jabber or XMPP servers. What this means is that you can have a few Jabber accounts on different servers and you can still use just one program to connect to all of them at the same time.

The full list of all known XMPP clients is very long. You can obviously try them all but below is a selection which is recommended by the Tigase team.  The selected programs might not be the best choice for you, but these programs have been tested and we can offer help with using them.  Here is a list of recommended instant messaging clients:

- http://psi-im.org/about[Psi]
Pure XMPP client. Although it supports only Jabber networks it is a very user friendly and comfortable program. It works on most popular operating systems like Linux, MS Windows, and Apple MacOS X.
- http://www.gajim.org/[Gajim]
This is another Jabber only client. Very user friendly and works on most of Linux distributions, FreeBSD, and MS Windows.
- http://www.pidgin.im/[Pidgin] (previously http://gaim.sourceforge.net/[Gaim])
This is not just a Jabber client. This type of application is called multicommunicator as apart from Jabber it supports many other instant messagin networks/protocols such as: AIM/ICQ, MSN, Yahoo, Gadu-Gadu, IRC, and a few others. So it is especially convenient if you have friends using other messaging networks. Pidgin works on most Linux distributions, and on MS Windows.
- http://kopete.kde.org/[Kopete]
This is a http://www.kde.org/[KDE] component and although it only works on Linux based system it also supports many of the most popular instant messaging protocols apart from Jabber like: AIM, Gadu-Gadu, ICQ, IRC, MSN, Yahoo.

Install the XMPP client of your choice and set up for a Tigase account.
