//[[genericTwoSessionManagers]]
Two or More SessionManagers
===========================
Artur Hefczyc <artur.hefczyc@tigase.net>
v2.0, June 2014: Reformatted for AsciiDoc.
:toc:
:numbered:
:website: http://tigase.net
:Date: 2010-04-06 21:18

In the most cases you use just one SessionManager object for your Tigase server installation. A single SM can handle multiple virtual domains with separate SSL certificates for each domain.

Sometimes, however you need very different configuration for each domain. For example you wish to use a separate database for a selected domain or you need a different set of plugins for each domain. For one domain you might want to allow user registration via XMPP and for another you might want to disable this feature.  In such a case you need to load more than one session manager.

This is generally not a problem. You just need to add another component in the configuration and adjust default settings.

The question is now how Tigase server knows to which session manager it has to forward packets received from the network. Mind, there is only one component responsible for handling client connections. So it needs to know somehow which session manager is receiver for certain packet.  Of course you set domain names in session manager too. But that is not enough. Tigase server supports cluster mode configuration where session manager can be running on a separate machine. So packet routings rules are not so simple to look at the domain name only. Therefore client connection manager (*c2s*) must know where is located the session manager responsible for handling the packet received from the network.

To solve the problem *routings* concept has been introduced. You can define packet routings based on the domain name set during XMPP stream initialization.  Each time *c2s* component receives packet from the network it tries to resolve destination component for the packet based on the current routings table. If you look in you server XML configuration file and search for *c2s* configuration section you can find routings node. Default configuration for routings table is quite simple. Just a single regular expression: 

[source,bash]
-------------------------------------
   <node name="routings">
    <map>
     <entry key=".+" type="String" value="sess-man%40tigase.org"/>
     <entry key="multi-mode" type="Boolean" value="true"/>
    </map>
   </node>
-------------------------------------
 
As you can see this routings table forwards all packets to a single destination - session manager located on the *tigase.org* server.

Let's say we have now two session managers each of them is responsible for a separate +domain.sm1@tigase.org+ handles requests for *tigase.org* and +sm2@tigase.net+ handles requests for domain *tigase.net.* So let's modify our default configuration to properly spread the traffic between these two sessiona managers: 

[source,bash]
-------------------------------------
   <node name="routings">
    <map>
     <entry key="tigase.org" type="String" value="sm1%40tigase.org"/>
     <entry key="tigase.net" type="String" value="sm2%40tigase.net"/>
     <entry key="multi-mode" type="Boolean" value="true"/>
    </map>
   </node>
-------------------------------------
 
Please remember that a key is a regular expression in Java style: link:http://java.sun.com/j2se/1.4.2/docs/api/java/util/regex/Pattern.html[Pattern.html]. You can match more than a single domain with the key, for example: _tigase.+_ to match all domains starting with *tigase*. The expression, however won't match domain: *xmpp.tigase.org*. To match this domain the expression would need to be: _.+tigase.+_.

