//[[tigaseAuthConnector]]
Tigase Auth Connector
=====================
Artur Hefczyc <artur.hefczyc@tigase.net>
v2.0, June 2014: Reformatted for AsciiDoc.
:toc:
:numbered:
:website: http://tigase.net
:Date: 2010-04-06 21:18

The Tigase Auth connector with shortcut name: *tigase-auth* is implemented in the class: link:http://projects.tigase.org/server/trac/browser/trunk/src/main/java/tigase/db/jdbc/TigaseAuth.java[tigase.db.jdbc.TigaseAuth]. It allows you to connect to any external database to perform user authentication.
You can find more details how to setup a custom connector in ////<<customAuthentication,////Custom Authentication Connectors guide.

To make this connector working you have to prepare your database to offer set of stored procedures for the Tigase server to perform all the authentication actions. The best description is the example schema with all the stored procedures defined. Please refer to the Tigase link:http://projects.tigase.org/server/trac/browser/trunk/database/[SVN repository] for the schema definition files.

Files with the stored procedures implementations are located in link:http://projects.tigase.org/server/trac/browser/trunk/database/mysql-schema-4-sp.schema[mysql-schema-4-sp.schema] for MySQL database and in link:http://projects.tigase.org/server/trac/browser/trunk/database/postgresql-schema-4-sp.schema[postgresql-schema-4-sp.schema] file for PostgreSQL database. You can also refer to the tables definition files to see how database is organized in our implementation: link:http://projects.tigase.org/server/trac/browser/trunk/database/mysql-schema-4.sql[mysql-schema-4.sql] file for MySQL database and link:http://projects.tigase.org/server/trac/browser/trunk/database/postgresql-schema-4.sql[postgresql-schema-4.sql] file for PostgreSQL database.

The absolute minimum of stored procedures you have to implement is:

- *TigUserLoginPlainPw* - to perform user authentication. The procedure is always called when the user tries to login to the XMPP server. This is the only procedure which must be implemented and actually must work.
- *TigUserLogout* - to perform user logout. The procedure is always called when the user logouts or disconnects from the server. This procedure must be implemented but it can be empty and can do nothing. It just needs to exist because Tigase expect it to exist and attempts to call it.

With these 2 above stored procedures you can only perform user login/logout on the external database. You can't register a user account, change user password or remove the user. In many cases this is fine as all the user management is handled by the external system.

If you however want to allow for account management via XMPP you have to implement also following procedures:

- *TigAddUserPlainPw* - to add a new user account
- *TigRemoveUser* - to remove existing user account
- *TigUpdatePasswordPlainPw* - to change a user password for existing account

