Basic System Checks
===================
Artur Hefczyc <artur.hefczyc@tigase.net>
v2.0, June 2014: Reformatted for AsciiDoc.
:toc:
:numbered:
:website: http://tigase.net
:Date: 2010-03-06 20:18

A while ago, I have written an article about Linux settings for high load systems. This is a description for just very basic settings which are essential to successfully run XMPP service for hundred of thousands online users.

Of course, high load and high traffic systems require much more tuning and adjustments. If you use selinux you have to be careful as it can interfere with the service while it is under a high load. Also some firewall settings may case problems as the system may decide it is under a DOS attack and can start blocking incoming connections or throttle the traffic.

In any case, there are some basic checks to do every time you deploy XMPP service to make sure it will function properly. I am trying to keep the article mentioned above up to date and add all the settings and parameters I discover while working with different installations. _If you have some suggestions for different values or different parameters to add, please let me know._

The article, while helpful, seems to be not enough though.

If you want to run a service on a few cluster nodes (5 or even 10), then manually checking every machine and adjusting these settings is quite annoying and it is very easy to forget about something.

To overcome this problem I started to work on a shell script which would run all the basic checks and report problems found. Ideally it should be also able to adjust some parameters for you.

I have just committed to the Tigase server link:https://svn.tigase.org/reps/tigase-server/trunk/scripts/[trunk/scripts/] repository a script called +machine-check.sh+. It performs all the basic checks from the article and also tries to adjust them when necessary. Have a link:https://svn.tigase.org/anon-websvn/filedetails.php?repname=tigase-server&path=%2Ftrunk%2Fscripts%2Fmachine-check.sh[look at the code] or link:https://svn.tigase.org/reps/tigase-server/trunk/scripts/machine-check.sh[check it out] and run for yourself.

Any comments or suggestions, as usually, very much appreciated.

