Tigase v7.1.0 announcement
==========================
:author: Daniel Wisnewski
:date: 2015-25-08 22:09


Introducing Tigase v7.1.0!  We have been working hard to improve and implement new features to the Tigase Sever program to give you a more secure, leaner, and better working XMPP server.

Notes and bug fixes to follow.

New JDK v8 required
-------------------
As Oracle has dropped support for version 7 of it's Java runtime environment and developer kit, we have moved to version 8 of the JDK.  Furthermore, some new features and fixes for Tigase Server now require the use of JDK v8 or later. Please upgrade your Java packages from link:http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[this link].

New Major Features
------------------

New HTTP API
~~~~~~~~~~~~
Tigase now features an HTTP API that not only allows web client chat, but administrators can change settings, manage users, and even write and run scripts all from the comfort of a browser window.   Furthermore, commands can be passed through this interface using REST to create and run custom scripts and commands.
We plan on expanding on the look and feel of this interface as time goes on, but in the meantime enjoy the real-time XMPP experience now with a user-friendly GUI.

New Admin HTTP interface
~~~~~~~~~~~~~~~~~~~~~~~~
Tigase now comes with its own build-in web XMPP client!  It can be accessed from http://yourhost.com:8080/ui/. For more details, see the Admin UI guide.

Added support for XEP-0334
~~~~~~~~~~~~~~~~~~~~~~~~~~
Added support to store offline messages for messages without body content. See link:http://xmpp.org/extensions/xep-0334.html[XEP-0334] for protocol details.

Maximum users setting for MUC
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Administrators can now set that maximum number of users allowed on specific MUCs.
Need tutorial

HTTP Rest  API Support
~~~~~~~~~~~~~~~~~~~~~~
Document Rest

Empty Nicknames
~~~~~~~~~~~~~~~
Tigase can now support users with empty nicknames so long as the following code is in init.properties
------
sess-man/plugins-conf/jabber\:iq\:roster/empty_name_enabled=true
------
#3308

Offline Message Limits
~~~~~~~~~~~~~~~~~~~~~~
https://projects.tigase.org/projects/verizon/wiki/Offline_Messages_-_limits

Offline Message Sink
~~~~~~~~~~~~~~~~~~~~
Documentation here https://projects.tigase.org/projects/verizon/wiki/Offline_Messages_-_sink

Adding Components to trusted list
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Components can now be added to trusted list and will be shared with all clustered servers. 3244/3336


New Minor Features
------------------
- Blocking extension is now enabled for all users.
- Allowing of +setPermissions+ on incoming packets before they are processed by plugins.
- Protected access to JDBC repository now enabled.
- IQ stanzas from disco no longer have delay delivery.
- Delivery errors are no longer run through preprocessors. 2596
- Messages properly stored until user presence is sent.
- Error for adding users already in db now returns Error 409 with +User exists+.
- VCard4 support added along with VCardTemp compatibility and integration.
- Ad-hoc scripts are now included in external components based on classes.
- Verification added to check against CUSTOM domain rules when submitted. 3230


Fixes
-----
tls-jdk-nss-bug-workaround-active is now disabled by default::
  This fix is disabled by default which may impact older OpenSSL versions that may no longer be supported.  You may enable this using an init.properties setting.

S2S connection multiplexing now has consistent behavior. Bug# 3181::

Username modification bugfix. Bug# 2118::
  Tigase now returns "" for blank usernames instead of string after a username has been made blank.

User roster behaves correctly. Bug# 663 & 1396::
  Tigase now waits for user authorization before users are added to a Roster.

Default Log level changed for cerain records. Task# 3150::
  All log entries with skipping admin script now have log level +FINEST+ instead of +CONFIG+

NPE in ad-hoc for managing external components fixed. Bug# 1488::

NPE in SessionManager checking SSL null connections fixed. Bug# 3166::

NPE in DomainFilter fixed.::

NPE when removing roster nickname fixed. Bug# 3274::

Wrapper.conf updated with current library folder for windows Service wrapper::

--net-buff-high-throughput now parses integers properly::
  Setting no longer reverts to default when new values are set.

Fixed error when compiling Tigase in Red Hat Enterprise Linux v6. Bug #3075::

Added missing class to IzPack installer::

PubSub Schema changed to be more compatible with MS SQL Bug# 3374::

JTDS MS SQL Server driver updated to v1.3.1::

Fixed NPE when presence was rebroadcasted to users who did not exit server gracefully. Bug# 3372::

Users removed VIA REST commands are now disconnected immediately. #3375::

Timeout changed for HTTP avatar reterival #3341:: //NextPlane

IQ Packet processing changed for packets sent to bare JID in Cluster mode #3341:: //NextPlane

Rosters are no longer re-saved when a user logs in and roster is read resulting in a performance boost. Bug# 3307::

Fixed Bug where if duplicate commands were sent to MS SQLServer a race condition would occur. Bug #3067::

Tigase.xml removed from documentation and default tigase.conf file.::

JabberIQVersion plugin now returns proper client information when requested from self. Bug#3249::

Streamlined primitive and Object array handling. Bug# 3034::

Websocket no longer loops when receiving stanzas between 32767 and 65535 bytes in size. Bug# 3259::

Correct presence status shows for contacts if authorization was accepted while user was offline. Bug #3203::

Fixed bug with C2S streams where server would not always overwrite from attribute with full JID in subcription-related presence stanzas. Bug #2003::

Fixed messages with AMP payload bound for plugins getting redirected to AMP for processing. Bug #3131::

Calculation of percentage of heap memory used in Statistics now selects proper heap. Bug #3126::

User Privacy lists now activate properly and does not wait for presence stanza to filter packets. Bug #3159::

+GetUserInfo+ ad-hoc command no longer omits information about local sessions when a remote session is active. Bug #3223::

Implemented a faster way to close stale connections using MS SQL server, reducing calm down time after large user disconnects. Bug #3200::

STARTTLS stream error on SSL sockets fixed.  Bug #2859/2997::
