[[mobileoptimizations]]
Mobile Optimizations
====================
Andrzej Wojcik <andrzejw@tigase.org>
v2.0, June 2014: Reformatted for AsciiDoc.
:toc:
:numbered:
:website: http://tigase.net/
:Date: 2012-05-22 17:57

Problem Description
-------------------

In default configuration stanzas are sent to client when processing is finished, but in mobile environment sending or receiving data drains battery due to use of radio. 

To save energy data should be sent to client only if it is important or client is waiting for it.

Solution
--------

When mobile client is entering inactive state it notifies server about it by sending following stanza:

[source,xml]
------------------------------------------------------------------
<iq type="set" id="xx">
<mobile 
  xmlns="http://tigase.org/protocol/mobile#v2" 
  enable="true"/>
</iq>
------------------------------------------------------------------

After receiving stanza server starts queueing presence stanza which should be send to mobile client. Any other stanza (such as iq or messenge) is sent immediately to the client.

When mobile client is entering active state it notifies server by sending following stanza:

[source,java]
------------------------------------------------------------------
<iq type="set" id="xx">
<mobile 
  xmlns="http://tigase.org/protocol/mobile#v2" 
  enable="false"/>
</iq>
------------------------------------------------------------------

After receiving stanza server sends all queued presence stanzas to the client.

Also all presence stanzas from queue will be sent if number of presence stanzas in queue will reach queue size limit. By default this limit is set to 50.

Queueing Algorithms
-------------------

There are two mobile optimization plugins for Tigase:

- *Mobile v1* - all presence stanzas are kept in queue
- *Mobile v2* - only last presence from each source is kept in queue


If you wish to activate you Mobile v1 plugin you need to send presented above with xmlns attribute value replaced with _http://tigase.org/protocol/mobile#v1_

Configuration
-------------

Mentioned plugins are not activated by default thus additional entries in the init.properties are required:

+--sm-plugins=+mobile_v1,+mobile_v2+

